// Code generated by Fern. DO NOT EDIT.

package client

import (
	account "github.com/usgm/usgm-go/account"
	addresses "github.com/usgm/usgm-go/addresses"
	bankaccounts "github.com/usgm/usgm-go/bankaccounts"
	core "github.com/usgm/usgm-go/core"
	folders "github.com/usgm/usgm-go/folders"
	internal "github.com/usgm/usgm-go/internal"
	mails "github.com/usgm/usgm-go/mails"
	option "github.com/usgm/usgm-go/option"
	sandbox "github.com/usgm/usgm-go/sandbox"
	scans "github.com/usgm/usgm-go/scans"
	shipments "github.com/usgm/usgm-go/shipments"
)

type Client struct {
	Mails        *mails.Client
	Scans        *scans.Client
	Shipments    *shipments.Client
	Folders      *folders.Client
	Addresses    *addresses.Client
	BankAccounts *bankaccounts.Client
	Account      *account.Client
	Sandbox      *sandbox.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Mails:        mails.NewClient(options),
		Scans:        scans.NewClient(options),
		Shipments:    shipments.NewClient(options),
		Folders:      folders.NewClient(options),
		Addresses:    addresses.NewClient(options),
		BankAccounts: bankaccounts.NewClient(options),
		Account:      account.NewClient(options),
		Sandbox:      sandbox.NewClient(options),
		options:      options,
		baseURL:      options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
