// Code generated by Fern. DO NOT EDIT.

package sandbox

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Populate your sandbox mailbox with sample mail items for testing
func (c *Client) Seed(
	ctx context.Context,
	opts ...option.RequestOption,
) (*usgm.SeedResultDto, error) {
	response, err := c.WithRawResponse.Seed(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Add one sample mail item to your sandbox mailbox, with optional overrides
func (c *Client) Seedmail(
	ctx context.Context,
	request *usgm.SeedSandboxMailDto,
	opts ...option.RequestOption,
) (*usgm.SeedMailResultDto, error) {
	response, err := c.WithRawResponse.Seedmail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Force a pending scan to completed in the sandbox for testing
func (c *Client) Completescan(
	ctx context.Context,
	request *usgm.CompleteSandboxScanDto,
	opts ...option.RequestOption,
) (*usgm.ScanDto, error) {
	response, err := c.WithRawResponse.Completescan(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
