// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
	time "time"
)

var (
	accountDtoFieldID          = big.NewInt(1 << 0)
	accountDtoFieldName        = big.NewInt(1 << 1)
	accountDtoFieldEmail       = big.NewInt(1 << 2)
	accountDtoFieldPhoneNumber = big.NewInt(1 << 3)
	accountDtoFieldStatus      = big.NewInt(1 << 4)
	accountDtoFieldBoxNumber   = big.NewInt(1 << 5)
	accountDtoFieldCreatedAt   = big.NewInt(1 << 6)
)

type AccountDto struct {
	// Account id (UUID).
	ID          string  `json:"id" url:"id"`
	Name        string  `json:"name" url:"name"`
	Email       string  `json:"email" url:"email"`
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// Account status as reported by USGM (e.g. `APPROVED`, `SUSPENDED`).
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// The PMB (private mailbox) number. Null until a mailbox is assigned.
	BoxNumber *string `json:"box_number,omitempty" url:"box_number,omitempty"`
	// Registration date.
	CreatedAt time.Time `json:"created_at" url:"created_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AccountDto) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccountDto) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AccountDto) GetEmail() string {
	if a == nil {
		return ""
	}
	return a.Email
}

func (a *AccountDto) GetPhoneNumber() *string {
	if a == nil {
		return nil
	}
	return a.PhoneNumber
}

func (a *AccountDto) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AccountDto) GetBoxNumber() *string {
	if a == nil {
		return nil
	}
	return a.BoxNumber
}

func (a *AccountDto) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *AccountDto) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AccountDto) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetID(id string) {
	a.ID = id
	a.require(accountDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetName(name string) {
	a.Name = name
	a.require(accountDtoFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetEmail(email string) {
	a.Email = email
	a.require(accountDtoFieldEmail)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetPhoneNumber(phoneNumber *string) {
	a.PhoneNumber = phoneNumber
	a.require(accountDtoFieldPhoneNumber)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetStatus(status *string) {
	a.Status = status
	a.require(accountDtoFieldStatus)
}

// SetBoxNumber sets the BoxNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetBoxNumber(boxNumber *string) {
	a.BoxNumber = boxNumber
	a.require(accountDtoFieldBoxNumber)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountDto) SetCreatedAt(createdAt time.Time) {
	a.CreatedAt = createdAt
	a.require(accountDtoFieldCreatedAt)
}

func (a *AccountDto) UnmarshalJSON(data []byte) error {
	type embed AccountDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AccountDto(unmarshaler.embed)
	a.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AccountDto) MarshalJSON() ([]byte, error) {
	type embed AccountDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*a),
		CreatedAt: internal.NewDateTime(a.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AccountDto) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	mailingAddressDtoFieldBoxNumber  = big.NewInt(1 << 0)
	mailingAddressDtoFieldLine1      = big.NewInt(1 << 1)
	mailingAddressDtoFieldLine2      = big.NewInt(1 << 2)
	mailingAddressDtoFieldLine3      = big.NewInt(1 << 3)
	mailingAddressDtoFieldCity       = big.NewInt(1 << 4)
	mailingAddressDtoFieldState      = big.NewInt(1 << 5)
	mailingAddressDtoFieldPostalCode = big.NewInt(1 << 6)
	mailingAddressDtoFieldCountry    = big.NewInt(1 << 7)
	mailingAddressDtoFieldFormatted  = big.NewInt(1 << 8)
)

type MailingAddressDto struct {
	// The PMB (private mailbox) number — include it on every inbound mail piece.
	BoxNumber  string  `json:"box_number" url:"box_number"`
	Line1      *string `json:"line1,omitempty" url:"line1,omitempty"`
	Line2      *string `json:"line2,omitempty" url:"line2,omitempty"`
	Line3      *string `json:"line3,omitempty" url:"line3,omitempty"`
	City       *string `json:"city,omitempty" url:"city,omitempty"`
	State      *string `json:"state,omitempty" url:"state,omitempty"`
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	Country    *string `json:"country,omitempty" url:"country,omitempty"`
	// The complete address on one line, ready to hand out: "<line1> PMB <box>, <city>, <state>, <postal_code>, <country>".
	Formatted string `json:"formatted" url:"formatted"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailingAddressDto) GetBoxNumber() string {
	if m == nil {
		return ""
	}
	return m.BoxNumber
}

func (m *MailingAddressDto) GetLine1() *string {
	if m == nil {
		return nil
	}
	return m.Line1
}

func (m *MailingAddressDto) GetLine2() *string {
	if m == nil {
		return nil
	}
	return m.Line2
}

func (m *MailingAddressDto) GetLine3() *string {
	if m == nil {
		return nil
	}
	return m.Line3
}

func (m *MailingAddressDto) GetCity() *string {
	if m == nil {
		return nil
	}
	return m.City
}

func (m *MailingAddressDto) GetState() *string {
	if m == nil {
		return nil
	}
	return m.State
}

func (m *MailingAddressDto) GetPostalCode() *string {
	if m == nil {
		return nil
	}
	return m.PostalCode
}

func (m *MailingAddressDto) GetCountry() *string {
	if m == nil {
		return nil
	}
	return m.Country
}

func (m *MailingAddressDto) GetFormatted() string {
	if m == nil {
		return ""
	}
	return m.Formatted
}

func (m *MailingAddressDto) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailingAddressDto) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetBoxNumber sets the BoxNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetBoxNumber(boxNumber string) {
	m.BoxNumber = boxNumber
	m.require(mailingAddressDtoFieldBoxNumber)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetLine1(line1 *string) {
	m.Line1 = line1
	m.require(mailingAddressDtoFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetLine2(line2 *string) {
	m.Line2 = line2
	m.require(mailingAddressDtoFieldLine2)
}

// SetLine3 sets the Line3 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetLine3(line3 *string) {
	m.Line3 = line3
	m.require(mailingAddressDtoFieldLine3)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetCity(city *string) {
	m.City = city
	m.require(mailingAddressDtoFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetState(state *string) {
	m.State = state
	m.require(mailingAddressDtoFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetPostalCode(postalCode *string) {
	m.PostalCode = postalCode
	m.require(mailingAddressDtoFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetCountry(country *string) {
	m.Country = country
	m.require(mailingAddressDtoFieldCountry)
}

// SetFormatted sets the Formatted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailingAddressDto) SetFormatted(formatted string) {
	m.Formatted = formatted
	m.require(mailingAddressDtoFieldFormatted)
}

func (m *MailingAddressDto) UnmarshalJSON(data []byte) error {
	type unmarshaler MailingAddressDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailingAddressDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailingAddressDto) MarshalJSON() ([]byte, error) {
	type embed MailingAddressDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailingAddressDto) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
