// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
)

var (
	createAddressDtoFieldType        = big.NewInt(1 << 0)
	createAddressDtoFieldName        = big.NewInt(1 << 1)
	createAddressDtoFieldLine1       = big.NewInt(1 << 2)
	createAddressDtoFieldLine2       = big.NewInt(1 << 3)
	createAddressDtoFieldLine3       = big.NewInt(1 << 4)
	createAddressDtoFieldCity        = big.NewInt(1 << 5)
	createAddressDtoFieldState       = big.NewInt(1 << 6)
	createAddressDtoFieldPostalCode  = big.NewInt(1 << 7)
	createAddressDtoFieldCountry     = big.NewInt(1 << 8)
	createAddressDtoFieldPhoneNumber = big.NewInt(1 << 9)
	createAddressDtoFieldTaxID       = big.NewInt(1 << 10)
)

type CreateAddressDto struct {
	// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
	Type        CreateAddressDtoType `json:"type" url:"-"`
	Name        string               `json:"name" url:"-"`
	Line1       string               `json:"line1" url:"-"`
	Line2       *string              `json:"line2,omitempty" url:"-"`
	Line3       *string              `json:"line3,omitempty" url:"-"`
	City        string               `json:"city" url:"-"`
	State       string               `json:"state" url:"-"`
	PostalCode  string               `json:"postal_code" url:"-"`
	Country     string               `json:"country" url:"-"`
	PhoneNumber string               `json:"phone_number" url:"-"`
	TaxID       *string              `json:"tax_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateAddressDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetType(type_ CreateAddressDtoType) {
	c.Type = type_
	c.require(createAddressDtoFieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetName(name string) {
	c.Name = name
	c.require(createAddressDtoFieldName)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetLine1(line1 string) {
	c.Line1 = line1
	c.require(createAddressDtoFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetLine2(line2 *string) {
	c.Line2 = line2
	c.require(createAddressDtoFieldLine2)
}

// SetLine3 sets the Line3 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetLine3(line3 *string) {
	c.Line3 = line3
	c.require(createAddressDtoFieldLine3)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetCity(city string) {
	c.City = city
	c.require(createAddressDtoFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetState(state string) {
	c.State = state
	c.require(createAddressDtoFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetPostalCode(postalCode string) {
	c.PostalCode = postalCode
	c.require(createAddressDtoFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetCountry(country string) {
	c.Country = country
	c.require(createAddressDtoFieldCountry)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetPhoneNumber(phoneNumber string) {
	c.PhoneNumber = phoneNumber
	c.require(createAddressDtoFieldPhoneNumber)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAddressDto) SetTaxID(taxID *string) {
	c.TaxID = taxID
	c.require(createAddressDtoFieldTaxID)
}

func (c *CreateAddressDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateAddressDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateAddressDto(body)
	return nil
}

func (c *CreateAddressDto) MarshalJSON() ([]byte, error) {
	type embed CreateAddressDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	addressesDeleteRequestFieldID = big.NewInt(1 << 0)
)

type AddressesDeleteRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddressesDeleteRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesDeleteRequest) SetID(id string) {
	a.ID = id
	a.require(addressesDeleteRequestFieldID)
}

var (
	addressesGetRequestFieldID = big.NewInt(1 << 0)
)

type AddressesGetRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddressesGetRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesGetRequest) SetID(id string) {
	a.ID = id
	a.require(addressesGetRequestFieldID)
}

var (
	addressesGetDefaultRequestFieldType = big.NewInt(1 << 0)
)

type AddressesGetDefaultRequest struct {
	// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
	Type AddressesGetDefaultRequestType `json:"-" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddressesGetDefaultRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesGetDefaultRequest) SetType(type_ AddressesGetDefaultRequestType) {
	a.Type = type_
	a.require(addressesGetDefaultRequestFieldType)
}

var (
	addressesListRequestFieldLimit  = big.NewInt(1 << 0)
	addressesListRequestFieldCursor = big.NewInt(1 << 1)
	addressesListRequestFieldType   = big.NewInt(1 << 2)
)

type AddressesListRequest struct {
	// Page size, capped at 100.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
	Type *AddressesListRequestType `json:"-" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddressesListRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesListRequest) SetLimit(limit *int) {
	a.Limit = limit
	a.require(addressesListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesListRequest) SetCursor(cursor *string) {
	a.Cursor = cursor
	a.require(addressesListRequestFieldCursor)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesListRequest) SetType(type_ *AddressesListRequestType) {
	a.Type = type_
	a.require(addressesListRequestFieldType)
}

var (
	addressesSetDefaultRequestFieldID = big.NewInt(1 << 0)
)

type AddressesSetDefaultRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddressesSetDefaultRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressesSetDefaultRequest) SetID(id string) {
	a.ID = id
	a.require(addressesSetDefaultRequestFieldID)
}

var (
	addressDtoFieldID          = big.NewInt(1 << 0)
	addressDtoFieldType        = big.NewInt(1 << 1)
	addressDtoFieldName        = big.NewInt(1 << 2)
	addressDtoFieldLine1       = big.NewInt(1 << 3)
	addressDtoFieldLine2       = big.NewInt(1 << 4)
	addressDtoFieldCity        = big.NewInt(1 << 5)
	addressDtoFieldState       = big.NewInt(1 << 6)
	addressDtoFieldPostalCode  = big.NewInt(1 << 7)
	addressDtoFieldCountry     = big.NewInt(1 << 8)
	addressDtoFieldLine3       = big.NewInt(1 << 9)
	addressDtoFieldPhoneNumber = big.NewInt(1 << 10)
	addressDtoFieldTaxID       = big.NewInt(1 << 11)
	addressDtoFieldIsDefault   = big.NewInt(1 << 12)
)

type AddressDto struct {
	// Address id (UUID).
	ID string `json:"id" url:"id"`
	// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
	Type AddressDtoType `json:"type" url:"type"`
	// Recipient name on the address.
	Name        *string `json:"name,omitempty" url:"name,omitempty"`
	Line1       *string `json:"line1,omitempty" url:"line1,omitempty"`
	Line2       *string `json:"line2,omitempty" url:"line2,omitempty"`
	City        *string `json:"city,omitempty" url:"city,omitempty"`
	State       *string `json:"state,omitempty" url:"state,omitempty"`
	PostalCode  *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	Country     *string `json:"country,omitempty" url:"country,omitempty"`
	Line3       *string `json:"line3,omitempty" url:"line3,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	TaxID       *string `json:"tax_id,omitempty" url:"tax_id,omitempty"`
	// The default address of its `type` — one per type.
	IsDefault bool `json:"is_default" url:"is_default"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddressDto) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AddressDto) GetType() AddressDtoType {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *AddressDto) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AddressDto) GetLine1() *string {
	if a == nil {
		return nil
	}
	return a.Line1
}

func (a *AddressDto) GetLine2() *string {
	if a == nil {
		return nil
	}
	return a.Line2
}

func (a *AddressDto) GetCity() *string {
	if a == nil {
		return nil
	}
	return a.City
}

func (a *AddressDto) GetState() *string {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *AddressDto) GetPostalCode() *string {
	if a == nil {
		return nil
	}
	return a.PostalCode
}

func (a *AddressDto) GetCountry() *string {
	if a == nil {
		return nil
	}
	return a.Country
}

func (a *AddressDto) GetLine3() *string {
	if a == nil {
		return nil
	}
	return a.Line3
}

func (a *AddressDto) GetPhoneNumber() *string {
	if a == nil {
		return nil
	}
	return a.PhoneNumber
}

func (a *AddressDto) GetTaxID() *string {
	if a == nil {
		return nil
	}
	return a.TaxID
}

func (a *AddressDto) GetIsDefault() bool {
	if a == nil {
		return false
	}
	return a.IsDefault
}

func (a *AddressDto) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddressDto) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetID(id string) {
	a.ID = id
	a.require(addressDtoFieldID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetType(type_ AddressDtoType) {
	a.Type = type_
	a.require(addressDtoFieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetName(name *string) {
	a.Name = name
	a.require(addressDtoFieldName)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetLine1(line1 *string) {
	a.Line1 = line1
	a.require(addressDtoFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetLine2(line2 *string) {
	a.Line2 = line2
	a.require(addressDtoFieldLine2)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetCity(city *string) {
	a.City = city
	a.require(addressDtoFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetState(state *string) {
	a.State = state
	a.require(addressDtoFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetPostalCode(postalCode *string) {
	a.PostalCode = postalCode
	a.require(addressDtoFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetCountry(country *string) {
	a.Country = country
	a.require(addressDtoFieldCountry)
}

// SetLine3 sets the Line3 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetLine3(line3 *string) {
	a.Line3 = line3
	a.require(addressDtoFieldLine3)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetPhoneNumber(phoneNumber *string) {
	a.PhoneNumber = phoneNumber
	a.require(addressDtoFieldPhoneNumber)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetTaxID(taxID *string) {
	a.TaxID = taxID
	a.require(addressDtoFieldTaxID)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressDto) SetIsDefault(isDefault bool) {
	a.IsDefault = isDefault
	a.require(addressDtoFieldIsDefault)
}

func (a *AddressDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AddressDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddressDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddressDto) MarshalJSON() ([]byte, error) {
	type embed AddressDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddressDto) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
type AddressDtoType string

const (
	AddressDtoTypeShipping AddressDtoType = "shipping"
	AddressDtoTypeDeposit  AddressDtoType = "deposit"
)

func NewAddressDtoTypeFromString(s string) (AddressDtoType, error) {
	switch s {
	case "shipping":
		return AddressDtoTypeShipping, nil
	case "deposit":
		return AddressDtoTypeDeposit, nil
	}
	var t AddressDtoType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddressDtoType) Ptr() *AddressDtoType {
	return &a
}

var (
	addressPageDtoFieldData       = big.NewInt(1 << 0)
	addressPageDtoFieldNextCursor = big.NewInt(1 << 1)
	addressPageDtoFieldTotalCount = big.NewInt(1 << 2)
)

type AddressPageDto struct {
	Data []*AddressPageDtoDataItem `json:"data" url:"data"`
	// Pass as `?cursor=` to fetch the next page. Null on the last page.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Total number of items matching this query across all pages.
	TotalCount int `json:"total_count" url:"total_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddressPageDto) GetData() []*AddressPageDtoDataItem {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AddressPageDto) GetNextCursor() *string {
	if a == nil {
		return nil
	}
	return a.NextCursor
}

func (a *AddressPageDto) GetTotalCount() int {
	if a == nil {
		return 0
	}
	return a.TotalCount
}

func (a *AddressPageDto) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddressPageDto) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDto) SetData(data []*AddressPageDtoDataItem) {
	a.Data = data
	a.require(addressPageDtoFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDto) SetNextCursor(nextCursor *string) {
	a.NextCursor = nextCursor
	a.require(addressPageDtoFieldNextCursor)
}

// SetTotalCount sets the TotalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDto) SetTotalCount(totalCount int) {
	a.TotalCount = totalCount
	a.require(addressPageDtoFieldTotalCount)
}

func (a *AddressPageDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AddressPageDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddressPageDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddressPageDto) MarshalJSON() ([]byte, error) {
	type embed AddressPageDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddressPageDto) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	addressPageDtoDataItemFieldID          = big.NewInt(1 << 0)
	addressPageDtoDataItemFieldType        = big.NewInt(1 << 1)
	addressPageDtoDataItemFieldName        = big.NewInt(1 << 2)
	addressPageDtoDataItemFieldLine1       = big.NewInt(1 << 3)
	addressPageDtoDataItemFieldLine2       = big.NewInt(1 << 4)
	addressPageDtoDataItemFieldCity        = big.NewInt(1 << 5)
	addressPageDtoDataItemFieldState       = big.NewInt(1 << 6)
	addressPageDtoDataItemFieldPostalCode  = big.NewInt(1 << 7)
	addressPageDtoDataItemFieldCountry     = big.NewInt(1 << 8)
	addressPageDtoDataItemFieldLine3       = big.NewInt(1 << 9)
	addressPageDtoDataItemFieldPhoneNumber = big.NewInt(1 << 10)
	addressPageDtoDataItemFieldTaxID       = big.NewInt(1 << 11)
	addressPageDtoDataItemFieldIsDefault   = big.NewInt(1 << 12)
)

type AddressPageDtoDataItem struct {
	// Address id (UUID).
	ID string `json:"id" url:"id"`
	// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
	Type AddressPageDtoDataItemType `json:"type" url:"type"`
	// Recipient name on the address.
	Name        *string `json:"name,omitempty" url:"name,omitempty"`
	Line1       *string `json:"line1,omitempty" url:"line1,omitempty"`
	Line2       *string `json:"line2,omitempty" url:"line2,omitempty"`
	City        *string `json:"city,omitempty" url:"city,omitempty"`
	State       *string `json:"state,omitempty" url:"state,omitempty"`
	PostalCode  *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	Country     *string `json:"country,omitempty" url:"country,omitempty"`
	Line3       *string `json:"line3,omitempty" url:"line3,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	TaxID       *string `json:"tax_id,omitempty" url:"tax_id,omitempty"`
	// The default address of its `type` — one per type.
	IsDefault bool `json:"is_default" url:"is_default"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddressPageDtoDataItem) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AddressPageDtoDataItem) GetType() AddressPageDtoDataItemType {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *AddressPageDtoDataItem) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AddressPageDtoDataItem) GetLine1() *string {
	if a == nil {
		return nil
	}
	return a.Line1
}

func (a *AddressPageDtoDataItem) GetLine2() *string {
	if a == nil {
		return nil
	}
	return a.Line2
}

func (a *AddressPageDtoDataItem) GetCity() *string {
	if a == nil {
		return nil
	}
	return a.City
}

func (a *AddressPageDtoDataItem) GetState() *string {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *AddressPageDtoDataItem) GetPostalCode() *string {
	if a == nil {
		return nil
	}
	return a.PostalCode
}

func (a *AddressPageDtoDataItem) GetCountry() *string {
	if a == nil {
		return nil
	}
	return a.Country
}

func (a *AddressPageDtoDataItem) GetLine3() *string {
	if a == nil {
		return nil
	}
	return a.Line3
}

func (a *AddressPageDtoDataItem) GetPhoneNumber() *string {
	if a == nil {
		return nil
	}
	return a.PhoneNumber
}

func (a *AddressPageDtoDataItem) GetTaxID() *string {
	if a == nil {
		return nil
	}
	return a.TaxID
}

func (a *AddressPageDtoDataItem) GetIsDefault() bool {
	if a == nil {
		return false
	}
	return a.IsDefault
}

func (a *AddressPageDtoDataItem) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddressPageDtoDataItem) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetID(id string) {
	a.ID = id
	a.require(addressPageDtoDataItemFieldID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetType(type_ AddressPageDtoDataItemType) {
	a.Type = type_
	a.require(addressPageDtoDataItemFieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetName(name *string) {
	a.Name = name
	a.require(addressPageDtoDataItemFieldName)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetLine1(line1 *string) {
	a.Line1 = line1
	a.require(addressPageDtoDataItemFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetLine2(line2 *string) {
	a.Line2 = line2
	a.require(addressPageDtoDataItemFieldLine2)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetCity(city *string) {
	a.City = city
	a.require(addressPageDtoDataItemFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetState(state *string) {
	a.State = state
	a.require(addressPageDtoDataItemFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetPostalCode(postalCode *string) {
	a.PostalCode = postalCode
	a.require(addressPageDtoDataItemFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetCountry(country *string) {
	a.Country = country
	a.require(addressPageDtoDataItemFieldCountry)
}

// SetLine3 sets the Line3 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetLine3(line3 *string) {
	a.Line3 = line3
	a.require(addressPageDtoDataItemFieldLine3)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetPhoneNumber(phoneNumber *string) {
	a.PhoneNumber = phoneNumber
	a.require(addressPageDtoDataItemFieldPhoneNumber)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetTaxID(taxID *string) {
	a.TaxID = taxID
	a.require(addressPageDtoDataItemFieldTaxID)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddressPageDtoDataItem) SetIsDefault(isDefault bool) {
	a.IsDefault = isDefault
	a.require(addressPageDtoDataItemFieldIsDefault)
}

func (a *AddressPageDtoDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler AddressPageDtoDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddressPageDtoDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddressPageDtoDataItem) MarshalJSON() ([]byte, error) {
	type embed AddressPageDtoDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddressPageDtoDataItem) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
type AddressPageDtoDataItemType string

const (
	AddressPageDtoDataItemTypeShipping AddressPageDtoDataItemType = "shipping"
	AddressPageDtoDataItemTypeDeposit  AddressPageDtoDataItemType = "deposit"
)

func NewAddressPageDtoDataItemTypeFromString(s string) (AddressPageDtoDataItemType, error) {
	switch s {
	case "shipping":
		return AddressPageDtoDataItemTypeShipping, nil
	case "deposit":
		return AddressPageDtoDataItemTypeDeposit, nil
	}
	var t AddressPageDtoDataItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddressPageDtoDataItemType) Ptr() *AddressPageDtoDataItemType {
	return &a
}

type AddressesGetDefaultRequestType string

const (
	AddressesGetDefaultRequestTypeShipping AddressesGetDefaultRequestType = "shipping"
	AddressesGetDefaultRequestTypeDeposit  AddressesGetDefaultRequestType = "deposit"
)

func NewAddressesGetDefaultRequestTypeFromString(s string) (AddressesGetDefaultRequestType, error) {
	switch s {
	case "shipping":
		return AddressesGetDefaultRequestTypeShipping, nil
	case "deposit":
		return AddressesGetDefaultRequestTypeDeposit, nil
	}
	var t AddressesGetDefaultRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddressesGetDefaultRequestType) Ptr() *AddressesGetDefaultRequestType {
	return &a
}

type AddressesListRequestType string

const (
	AddressesListRequestTypeShipping AddressesListRequestType = "shipping"
	AddressesListRequestTypeDeposit  AddressesListRequestType = "deposit"
)

func NewAddressesListRequestTypeFromString(s string) (AddressesListRequestType, error) {
	switch s {
	case "shipping":
		return AddressesListRequestTypeShipping, nil
	case "deposit":
		return AddressesListRequestTypeDeposit, nil
	}
	var t AddressesListRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddressesListRequestType) Ptr() *AddressesListRequestType {
	return &a
}

// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
type CreateAddressDtoType string

const (
	CreateAddressDtoTypeShipping CreateAddressDtoType = "shipping"
	CreateAddressDtoTypeDeposit  CreateAddressDtoType = "deposit"
)

func NewCreateAddressDtoTypeFromString(s string) (CreateAddressDtoType, error) {
	switch s {
	case "shipping":
		return CreateAddressDtoTypeShipping, nil
	case "deposit":
		return CreateAddressDtoTypeDeposit, nil
	}
	var t CreateAddressDtoType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateAddressDtoType) Ptr() *CreateAddressDtoType {
	return &c
}

// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
type UpdateAddressDtoType string

const (
	UpdateAddressDtoTypeShipping UpdateAddressDtoType = "shipping"
	UpdateAddressDtoTypeDeposit  UpdateAddressDtoType = "deposit"
)

func NewUpdateAddressDtoTypeFromString(s string) (UpdateAddressDtoType, error) {
	switch s {
	case "shipping":
		return UpdateAddressDtoTypeShipping, nil
	case "deposit":
		return UpdateAddressDtoTypeDeposit, nil
	}
	var t UpdateAddressDtoType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateAddressDtoType) Ptr() *UpdateAddressDtoType {
	return &u
}

var (
	updateAddressDtoFieldID          = big.NewInt(1 << 0)
	updateAddressDtoFieldType        = big.NewInt(1 << 1)
	updateAddressDtoFieldName        = big.NewInt(1 << 2)
	updateAddressDtoFieldLine1       = big.NewInt(1 << 3)
	updateAddressDtoFieldLine2       = big.NewInt(1 << 4)
	updateAddressDtoFieldLine3       = big.NewInt(1 << 5)
	updateAddressDtoFieldCity        = big.NewInt(1 << 6)
	updateAddressDtoFieldState       = big.NewInt(1 << 7)
	updateAddressDtoFieldPostalCode  = big.NewInt(1 << 8)
	updateAddressDtoFieldCountry     = big.NewInt(1 << 9)
	updateAddressDtoFieldPhoneNumber = big.NewInt(1 << 10)
	updateAddressDtoFieldTaxID       = big.NewInt(1 << 11)
)

type UpdateAddressDto struct {
	ID string `json:"-" url:"-"`
	// `shipping` = a shipment destination; `deposit` = where check deposits are sent.
	Type        *UpdateAddressDtoType `json:"type,omitempty" url:"-"`
	Name        *string               `json:"name,omitempty" url:"-"`
	Line1       *string               `json:"line1,omitempty" url:"-"`
	Line2       *string               `json:"line2,omitempty" url:"-"`
	Line3       *string               `json:"line3,omitempty" url:"-"`
	City        *string               `json:"city,omitempty" url:"-"`
	State       *string               `json:"state,omitempty" url:"-"`
	PostalCode  *string               `json:"postal_code,omitempty" url:"-"`
	Country     *string               `json:"country,omitempty" url:"-"`
	PhoneNumber *string               `json:"phone_number,omitempty" url:"-"`
	TaxID       *string               `json:"tax_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateAddressDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetID(id string) {
	u.ID = id
	u.require(updateAddressDtoFieldID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetType(type_ *UpdateAddressDtoType) {
	u.Type = type_
	u.require(updateAddressDtoFieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetName(name *string) {
	u.Name = name
	u.require(updateAddressDtoFieldName)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetLine1(line1 *string) {
	u.Line1 = line1
	u.require(updateAddressDtoFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetLine2(line2 *string) {
	u.Line2 = line2
	u.require(updateAddressDtoFieldLine2)
}

// SetLine3 sets the Line3 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetLine3(line3 *string) {
	u.Line3 = line3
	u.require(updateAddressDtoFieldLine3)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetCity(city *string) {
	u.City = city
	u.require(updateAddressDtoFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetState(state *string) {
	u.State = state
	u.require(updateAddressDtoFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetPostalCode(postalCode *string) {
	u.PostalCode = postalCode
	u.require(updateAddressDtoFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetCountry(country *string) {
	u.Country = country
	u.require(updateAddressDtoFieldCountry)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetPhoneNumber(phoneNumber *string) {
	u.PhoneNumber = phoneNumber
	u.require(updateAddressDtoFieldPhoneNumber)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAddressDto) SetTaxID(taxID *string) {
	u.TaxID = taxID
	u.require(updateAddressDtoFieldTaxID)
}

func (u *UpdateAddressDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateAddressDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateAddressDto(body)
	return nil
}

func (u *UpdateAddressDto) MarshalJSON() ([]byte, error) {
	type embed UpdateAddressDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
