// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
	time "time"
)

var (
	createFolderDtoFieldName  = big.NewInt(1 << 0)
	createFolderDtoFieldColor = big.NewInt(1 << 1)
)

type CreateFolderDto struct {
	Name  string  `json:"name" url:"-"`
	Color *string `json:"color,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateFolderDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFolderDto) SetName(name string) {
	c.Name = name
	c.require(createFolderDtoFieldName)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFolderDto) SetColor(color *string) {
	c.Color = color
	c.require(createFolderDtoFieldColor)
}

func (c *CreateFolderDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateFolderDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateFolderDto(body)
	return nil
}

func (c *CreateFolderDto) MarshalJSON() ([]byte, error) {
	type embed CreateFolderDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	foldersDeleteRequestFieldID = big.NewInt(1 << 0)
)

type FoldersDeleteRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FoldersDeleteRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FoldersDeleteRequest) SetID(id string) {
	f.ID = id
	f.require(foldersDeleteRequestFieldID)
}

var (
	foldersGetRequestFieldID = big.NewInt(1 << 0)
)

type FoldersGetRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FoldersGetRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FoldersGetRequest) SetID(id string) {
	f.ID = id
	f.require(foldersGetRequestFieldID)
}

var (
	folderDtoFieldID        = big.NewInt(1 << 0)
	folderDtoFieldName      = big.NewInt(1 << 1)
	folderDtoFieldColor     = big.NewInt(1 << 2)
	folderDtoFieldCreatedOn = big.NewInt(1 << 3)
	folderDtoFieldUpdatedOn = big.NewInt(1 << 4)
)

type FolderDto struct {
	// Folder id (numeric string) — mail items reference it as `folder_id`.
	ID   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`
	// Hex color like `#4BB94B`.
	Color     *string   `json:"color,omitempty" url:"color,omitempty"`
	CreatedOn time.Time `json:"created_on" url:"created_on"`
	UpdatedOn time.Time `json:"updated_on" url:"updated_on"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FolderDto) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FolderDto) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FolderDto) GetColor() *string {
	if f == nil {
		return nil
	}
	return f.Color
}

func (f *FolderDto) GetCreatedOn() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedOn
}

func (f *FolderDto) GetUpdatedOn() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.UpdatedOn
}

func (f *FolderDto) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FolderDto) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderDto) SetID(id string) {
	f.ID = id
	f.require(folderDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderDto) SetName(name string) {
	f.Name = name
	f.require(folderDtoFieldName)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderDto) SetColor(color *string) {
	f.Color = color
	f.require(folderDtoFieldColor)
}

// SetCreatedOn sets the CreatedOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderDto) SetCreatedOn(createdOn time.Time) {
	f.CreatedOn = createdOn
	f.require(folderDtoFieldCreatedOn)
}

// SetUpdatedOn sets the UpdatedOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderDto) SetUpdatedOn(updatedOn time.Time) {
	f.UpdatedOn = updatedOn
	f.require(folderDtoFieldUpdatedOn)
}

func (f *FolderDto) UnmarshalJSON(data []byte) error {
	type embed FolderDto
	var unmarshaler = struct {
		embed
		CreatedOn *internal.DateTime `json:"created_on"`
		UpdatedOn *internal.DateTime `json:"updated_on"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderDto(unmarshaler.embed)
	f.CreatedOn = unmarshaler.CreatedOn.Time()
	f.UpdatedOn = unmarshaler.UpdatedOn.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderDto) MarshalJSON() ([]byte, error) {
	type embed FolderDto
	var marshaler = struct {
		embed
		CreatedOn *internal.DateTime `json:"created_on"`
		UpdatedOn *internal.DateTime `json:"updated_on"`
	}{
		embed:     embed(*f),
		CreatedOn: internal.NewDateTime(f.CreatedOn),
		UpdatedOn: internal.NewDateTime(f.UpdatedOn),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FolderDto) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	folderListDtoFieldData = big.NewInt(1 << 0)
)

type FolderListDto struct {
	Data []*FolderListDtoDataItem `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FolderListDto) GetData() []*FolderListDtoDataItem {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FolderListDto) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FolderListDto) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderListDto) SetData(data []*FolderListDtoDataItem) {
	f.Data = data
	f.require(folderListDtoFieldData)
}

func (f *FolderListDto) UnmarshalJSON(data []byte) error {
	type unmarshaler FolderListDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FolderListDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderListDto) MarshalJSON() ([]byte, error) {
	type embed FolderListDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FolderListDto) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	folderListDtoDataItemFieldID        = big.NewInt(1 << 0)
	folderListDtoDataItemFieldName      = big.NewInt(1 << 1)
	folderListDtoDataItemFieldColor     = big.NewInt(1 << 2)
	folderListDtoDataItemFieldCreatedOn = big.NewInt(1 << 3)
	folderListDtoDataItemFieldUpdatedOn = big.NewInt(1 << 4)
)

type FolderListDtoDataItem struct {
	// Folder id (numeric string) — mail items reference it as `folder_id`.
	ID   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`
	// Hex color like `#4BB94B`.
	Color     *string   `json:"color,omitempty" url:"color,omitempty"`
	CreatedOn time.Time `json:"created_on" url:"created_on"`
	UpdatedOn time.Time `json:"updated_on" url:"updated_on"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FolderListDtoDataItem) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FolderListDtoDataItem) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FolderListDtoDataItem) GetColor() *string {
	if f == nil {
		return nil
	}
	return f.Color
}

func (f *FolderListDtoDataItem) GetCreatedOn() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedOn
}

func (f *FolderListDtoDataItem) GetUpdatedOn() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.UpdatedOn
}

func (f *FolderListDtoDataItem) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FolderListDtoDataItem) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderListDtoDataItem) SetID(id string) {
	f.ID = id
	f.require(folderListDtoDataItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderListDtoDataItem) SetName(name string) {
	f.Name = name
	f.require(folderListDtoDataItemFieldName)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderListDtoDataItem) SetColor(color *string) {
	f.Color = color
	f.require(folderListDtoDataItemFieldColor)
}

// SetCreatedOn sets the CreatedOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderListDtoDataItem) SetCreatedOn(createdOn time.Time) {
	f.CreatedOn = createdOn
	f.require(folderListDtoDataItemFieldCreatedOn)
}

// SetUpdatedOn sets the UpdatedOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FolderListDtoDataItem) SetUpdatedOn(updatedOn time.Time) {
	f.UpdatedOn = updatedOn
	f.require(folderListDtoDataItemFieldUpdatedOn)
}

func (f *FolderListDtoDataItem) UnmarshalJSON(data []byte) error {
	type embed FolderListDtoDataItem
	var unmarshaler = struct {
		embed
		CreatedOn *internal.DateTime `json:"created_on"`
		UpdatedOn *internal.DateTime `json:"updated_on"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FolderListDtoDataItem(unmarshaler.embed)
	f.CreatedOn = unmarshaler.CreatedOn.Time()
	f.UpdatedOn = unmarshaler.UpdatedOn.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FolderListDtoDataItem) MarshalJSON() ([]byte, error) {
	type embed FolderListDtoDataItem
	var marshaler = struct {
		embed
		CreatedOn *internal.DateTime `json:"created_on"`
		UpdatedOn *internal.DateTime `json:"updated_on"`
	}{
		embed:     embed(*f),
		CreatedOn: internal.NewDateTime(f.CreatedOn),
		UpdatedOn: internal.NewDateTime(f.UpdatedOn),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FolderListDtoDataItem) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	updateFolderDtoFieldID    = big.NewInt(1 << 0)
	updateFolderDtoFieldName  = big.NewInt(1 << 1)
	updateFolderDtoFieldColor = big.NewInt(1 << 2)
)

type UpdateFolderDto struct {
	ID    string  `json:"-" url:"-"`
	Name  *string `json:"name,omitempty" url:"-"`
	Color *string `json:"color,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateFolderDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateFolderDto) SetID(id string) {
	u.ID = id
	u.require(updateFolderDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateFolderDto) SetName(name *string) {
	u.Name = name
	u.require(updateFolderDtoFieldName)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateFolderDto) SetColor(color *string) {
	u.Color = color
	u.require(updateFolderDtoFieldColor)
}

func (u *UpdateFolderDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateFolderDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateFolderDto(body)
	return nil
}

func (u *UpdateFolderDto) MarshalJSON() ([]byte, error) {
	type embed UpdateFolderDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
