// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
	time "time"
)

var (
	mailsArchiveRequestFieldID = big.NewInt(1 << 0)
)

type MailsArchiveRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MailsArchiveRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsArchiveRequest) SetID(id string) {
	m.ID = id
	m.require(mailsArchiveRequestFieldID)
}

var (
	mailsDiscardRequestFieldID = big.NewInt(1 << 0)
)

type MailsDiscardRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MailsDiscardRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsDiscardRequest) SetID(id string) {
	m.ID = id
	m.require(mailsDiscardRequestFieldID)
}

var (
	mailsGetRequestFieldID = big.NewInt(1 << 0)
)

type MailsGetRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MailsGetRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsGetRequest) SetID(id string) {
	m.ID = id
	m.require(mailsGetRequestFieldID)
}

var (
	mailsListRequestFieldLimit      = big.NewInt(1 << 0)
	mailsListRequestFieldCursor     = big.NewInt(1 << 1)
	mailsListRequestFieldStatus     = big.NewInt(1 << 2)
	mailsListRequestFieldMailType   = big.NewInt(1 << 3)
	mailsListRequestFieldFolderID   = big.NewInt(1 << 4)
	mailsListRequestFieldSearch     = big.NewInt(1 << 5)
	mailsListRequestFieldScanStatus = big.NewInt(1 << 6)
	mailsListRequestFieldSort       = big.NewInt(1 << 7)
	mailsListRequestFieldArrived    = big.NewInt(1 << 8)
	mailsListRequestFieldIsRead     = big.NewInt(1 << 9)
)

type MailsListRequest struct {
	// Page size, capped at 100.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.
	Cursor   *string                         `json:"-" url:"cursor,omitempty"`
	Status   []*MailsListRequestStatusItem   `json:"-" url:"status,omitempty"`
	MailType []*MailsListRequestMailTypeItem `json:"-" url:"mail_type,omitempty"`
	FolderID *int                            `json:"-" url:"folder_id,omitempty"`
	Search   *string                         `json:"-" url:"search,omitempty"`
	// Filter by the item’s scan state; `none` selects items with no scan.
	ScanStatus []*MailsListRequestScanStatusItem `json:"-" url:"scan_status,omitempty"`
	Sort       *MailsListRequestSort             `json:"-" url:"sort,omitempty"`
	Arrived    *MailsListRequestArrived          `json:"-" url:"arrived,omitempty"`
	IsRead     *MailsListRequestIsRead           `json:"-" url:"is_read,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MailsListRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetLimit(limit *int) {
	m.Limit = limit
	m.require(mailsListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetCursor(cursor *string) {
	m.Cursor = cursor
	m.require(mailsListRequestFieldCursor)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetStatus(status []*MailsListRequestStatusItem) {
	m.Status = status
	m.require(mailsListRequestFieldStatus)
}

// SetMailType sets the MailType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetMailType(mailType []*MailsListRequestMailTypeItem) {
	m.MailType = mailType
	m.require(mailsListRequestFieldMailType)
}

// SetFolderID sets the FolderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetFolderID(folderID *int) {
	m.FolderID = folderID
	m.require(mailsListRequestFieldFolderID)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetSearch(search *string) {
	m.Search = search
	m.require(mailsListRequestFieldSearch)
}

// SetScanStatus sets the ScanStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetScanStatus(scanStatus []*MailsListRequestScanStatusItem) {
	m.ScanStatus = scanStatus
	m.require(mailsListRequestFieldScanStatus)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetSort(sort *MailsListRequestSort) {
	m.Sort = sort
	m.require(mailsListRequestFieldSort)
}

// SetArrived sets the Arrived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetArrived(arrived *MailsListRequestArrived) {
	m.Arrived = arrived
	m.require(mailsListRequestFieldArrived)
}

// SetIsRead sets the IsRead field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsListRequest) SetIsRead(isRead *MailsListRequestIsRead) {
	m.IsRead = isRead
	m.require(mailsListRequestFieldIsRead)
}

var (
	mailDetailDtoFieldID                = big.NewInt(1 << 0)
	mailDetailDtoFieldIsRead            = big.NewInt(1 << 1)
	mailDetailDtoFieldMailStatus        = big.NewInt(1 << 2)
	mailDetailDtoFieldMailType          = big.NewInt(1 << 3)
	mailDetailDtoFieldSenderName        = big.NewInt(1 << 4)
	mailDetailDtoFieldRecipientName     = big.NewInt(1 << 5)
	mailDetailDtoFieldArrivalDate       = big.NewInt(1 << 6)
	mailDetailDtoFieldEnvelopeImageURL  = big.NewInt(1 << 7)
	mailDetailDtoFieldQuarantineReason  = big.NewInt(1 << 8)
	mailDetailDtoFieldScan              = big.NewInt(1 << 9)
	mailDetailDtoFieldMailTypeLabel     = big.NewInt(1 << 10)
	mailDetailDtoFieldMeasurement       = big.NewInt(1 << 11)
	mailDetailDtoFieldWeight            = big.NewInt(1 << 12)
	mailDetailDtoFieldTrackingNumber    = big.NewInt(1 << 13)
	mailDetailDtoFieldSenderAddress     = big.NewInt(1 << 14)
	mailDetailDtoFieldHasStorageCharges = big.NewInt(1 << 15)
	mailDetailDtoFieldFolder            = big.NewInt(1 << 16)
)

type MailDetailDto struct {
	// Mail item id (numeric string).
	ID     string `json:"id" url:"id"`
	IsRead bool   `json:"is_read" url:"is_read"`
	// Lifecycle status as reported by the mailroom.
	MailStatus    string  `json:"mail_status" url:"mail_status"`
	MailType      string  `json:"mail_type" url:"mail_type"`
	SenderName    *string `json:"sender_name,omitempty" url:"sender_name,omitempty"`
	RecipientName *string `json:"recipient_name,omitempty" url:"recipient_name,omitempty"`
	// When the item arrived at the facility.
	ArrivalDate *time.Time `json:"arrival_date,omitempty" url:"arrival_date,omitempty"`
	// Photo of the item/envelope.
	EnvelopeImageURL *string `json:"envelope_image_url,omitempty" url:"envelope_image_url,omitempty"`
	QuarantineReason *string `json:"quarantine_reason,omitempty" url:"quarantine_reason,omitempty"`
	// The scan requested for this item, when one exists.
	Scan *MailDetailDtoScan `json:"scan,omitempty" url:"scan,omitempty"`
	// Human-readable form of `mail_type` (e.g. "Large Letter").
	MailTypeLabel string `json:"mail_type_label" url:"mail_type_label"`
	// Item dimensions, in inches.
	Measurement *MailDetailDtoMeasurement `json:"measurement" url:"measurement"`
	// Item weight, in pounds.
	Weight float64 `json:"weight" url:"weight"`
	// Inbound carrier tracking number, when one was captured.
	TrackingNumber *string `json:"tracking_number,omitempty" url:"tracking_number,omitempty"`
	SenderAddress  *string `json:"sender_address,omitempty" url:"sender_address,omitempty"`
	// Whether the item is currently accruing storage charges.
	HasStorageCharges bool                 `json:"has_storage_charges" url:"has_storage_charges"`
	Folder            *MailDetailDtoFolder `json:"folder,omitempty" url:"folder,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailDetailDto) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MailDetailDto) GetIsRead() bool {
	if m == nil {
		return false
	}
	return m.IsRead
}

func (m *MailDetailDto) GetMailStatus() string {
	if m == nil {
		return ""
	}
	return m.MailStatus
}

func (m *MailDetailDto) GetMailType() string {
	if m == nil {
		return ""
	}
	return m.MailType
}

func (m *MailDetailDto) GetSenderName() *string {
	if m == nil {
		return nil
	}
	return m.SenderName
}

func (m *MailDetailDto) GetRecipientName() *string {
	if m == nil {
		return nil
	}
	return m.RecipientName
}

func (m *MailDetailDto) GetArrivalDate() *time.Time {
	if m == nil {
		return nil
	}
	return m.ArrivalDate
}

func (m *MailDetailDto) GetEnvelopeImageURL() *string {
	if m == nil {
		return nil
	}
	return m.EnvelopeImageURL
}

func (m *MailDetailDto) GetQuarantineReason() *string {
	if m == nil {
		return nil
	}
	return m.QuarantineReason
}

func (m *MailDetailDto) GetScan() *MailDetailDtoScan {
	if m == nil {
		return nil
	}
	return m.Scan
}

func (m *MailDetailDto) GetMailTypeLabel() string {
	if m == nil {
		return ""
	}
	return m.MailTypeLabel
}

func (m *MailDetailDto) GetMeasurement() *MailDetailDtoMeasurement {
	if m == nil {
		return nil
	}
	return m.Measurement
}

func (m *MailDetailDto) GetWeight() float64 {
	if m == nil {
		return 0
	}
	return m.Weight
}

func (m *MailDetailDto) GetTrackingNumber() *string {
	if m == nil {
		return nil
	}
	return m.TrackingNumber
}

func (m *MailDetailDto) GetSenderAddress() *string {
	if m == nil {
		return nil
	}
	return m.SenderAddress
}

func (m *MailDetailDto) GetHasStorageCharges() bool {
	if m == nil {
		return false
	}
	return m.HasStorageCharges
}

func (m *MailDetailDto) GetFolder() *MailDetailDtoFolder {
	if m == nil {
		return nil
	}
	return m.Folder
}

func (m *MailDetailDto) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailDetailDto) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetID(id string) {
	m.ID = id
	m.require(mailDetailDtoFieldID)
}

// SetIsRead sets the IsRead field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetIsRead(isRead bool) {
	m.IsRead = isRead
	m.require(mailDetailDtoFieldIsRead)
}

// SetMailStatus sets the MailStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetMailStatus(mailStatus string) {
	m.MailStatus = mailStatus
	m.require(mailDetailDtoFieldMailStatus)
}

// SetMailType sets the MailType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetMailType(mailType string) {
	m.MailType = mailType
	m.require(mailDetailDtoFieldMailType)
}

// SetSenderName sets the SenderName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetSenderName(senderName *string) {
	m.SenderName = senderName
	m.require(mailDetailDtoFieldSenderName)
}

// SetRecipientName sets the RecipientName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetRecipientName(recipientName *string) {
	m.RecipientName = recipientName
	m.require(mailDetailDtoFieldRecipientName)
}

// SetArrivalDate sets the ArrivalDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetArrivalDate(arrivalDate *time.Time) {
	m.ArrivalDate = arrivalDate
	m.require(mailDetailDtoFieldArrivalDate)
}

// SetEnvelopeImageURL sets the EnvelopeImageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetEnvelopeImageURL(envelopeImageURL *string) {
	m.EnvelopeImageURL = envelopeImageURL
	m.require(mailDetailDtoFieldEnvelopeImageURL)
}

// SetQuarantineReason sets the QuarantineReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetQuarantineReason(quarantineReason *string) {
	m.QuarantineReason = quarantineReason
	m.require(mailDetailDtoFieldQuarantineReason)
}

// SetScan sets the Scan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetScan(scan *MailDetailDtoScan) {
	m.Scan = scan
	m.require(mailDetailDtoFieldScan)
}

// SetMailTypeLabel sets the MailTypeLabel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetMailTypeLabel(mailTypeLabel string) {
	m.MailTypeLabel = mailTypeLabel
	m.require(mailDetailDtoFieldMailTypeLabel)
}

// SetMeasurement sets the Measurement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetMeasurement(measurement *MailDetailDtoMeasurement) {
	m.Measurement = measurement
	m.require(mailDetailDtoFieldMeasurement)
}

// SetWeight sets the Weight field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetWeight(weight float64) {
	m.Weight = weight
	m.require(mailDetailDtoFieldWeight)
}

// SetTrackingNumber sets the TrackingNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetTrackingNumber(trackingNumber *string) {
	m.TrackingNumber = trackingNumber
	m.require(mailDetailDtoFieldTrackingNumber)
}

// SetSenderAddress sets the SenderAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetSenderAddress(senderAddress *string) {
	m.SenderAddress = senderAddress
	m.require(mailDetailDtoFieldSenderAddress)
}

// SetHasStorageCharges sets the HasStorageCharges field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetHasStorageCharges(hasStorageCharges bool) {
	m.HasStorageCharges = hasStorageCharges
	m.require(mailDetailDtoFieldHasStorageCharges)
}

// SetFolder sets the Folder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDto) SetFolder(folder *MailDetailDtoFolder) {
	m.Folder = folder
	m.require(mailDetailDtoFieldFolder)
}

func (m *MailDetailDto) UnmarshalJSON(data []byte) error {
	type embed MailDetailDto
	var unmarshaler = struct {
		embed
		ArrivalDate *internal.DateTime `json:"arrival_date,omitempty"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = MailDetailDto(unmarshaler.embed)
	m.ArrivalDate = unmarshaler.ArrivalDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailDetailDto) MarshalJSON() ([]byte, error) {
	type embed MailDetailDto
	var marshaler = struct {
		embed
		ArrivalDate *internal.DateTime `json:"arrival_date,omitempty"`
	}{
		embed:       embed(*m),
		ArrivalDate: internal.NewOptionalDateTime(m.ArrivalDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailDetailDto) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mailDetailDtoFolderFieldID    = big.NewInt(1 << 0)
	mailDetailDtoFolderFieldName  = big.NewInt(1 << 1)
	mailDetailDtoFolderFieldColor = big.NewInt(1 << 2)
)

type MailDetailDtoFolder struct {
	ID    string  `json:"id" url:"id"`
	Name  string  `json:"name" url:"name"`
	Color *string `json:"color,omitempty" url:"color,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailDetailDtoFolder) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MailDetailDtoFolder) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MailDetailDtoFolder) GetColor() *string {
	if m == nil {
		return nil
	}
	return m.Color
}

func (m *MailDetailDtoFolder) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailDetailDtoFolder) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoFolder) SetID(id string) {
	m.ID = id
	m.require(mailDetailDtoFolderFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoFolder) SetName(name string) {
	m.Name = name
	m.require(mailDetailDtoFolderFieldName)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoFolder) SetColor(color *string) {
	m.Color = color
	m.require(mailDetailDtoFolderFieldColor)
}

func (m *MailDetailDtoFolder) UnmarshalJSON(data []byte) error {
	type unmarshaler MailDetailDtoFolder
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailDetailDtoFolder(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailDetailDtoFolder) MarshalJSON() ([]byte, error) {
	type embed MailDetailDtoFolder
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailDetailDtoFolder) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// Item dimensions, in inches.
var (
	mailDetailDtoMeasurementFieldWidth  = big.NewInt(1 << 0)
	mailDetailDtoMeasurementFieldHeight = big.NewInt(1 << 1)
	mailDetailDtoMeasurementFieldLength = big.NewInt(1 << 2)
)

type MailDetailDtoMeasurement struct {
	// Inches.
	Width float64 `json:"width" url:"width"`
	// Inches.
	Height float64 `json:"height" url:"height"`
	// Inches.
	Length float64 `json:"length" url:"length"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailDetailDtoMeasurement) GetWidth() float64 {
	if m == nil {
		return 0
	}
	return m.Width
}

func (m *MailDetailDtoMeasurement) GetHeight() float64 {
	if m == nil {
		return 0
	}
	return m.Height
}

func (m *MailDetailDtoMeasurement) GetLength() float64 {
	if m == nil {
		return 0
	}
	return m.Length
}

func (m *MailDetailDtoMeasurement) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailDetailDtoMeasurement) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetWidth sets the Width field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoMeasurement) SetWidth(width float64) {
	m.Width = width
	m.require(mailDetailDtoMeasurementFieldWidth)
}

// SetHeight sets the Height field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoMeasurement) SetHeight(height float64) {
	m.Height = height
	m.require(mailDetailDtoMeasurementFieldHeight)
}

// SetLength sets the Length field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoMeasurement) SetLength(length float64) {
	m.Length = length
	m.require(mailDetailDtoMeasurementFieldLength)
}

func (m *MailDetailDtoMeasurement) UnmarshalJSON(data []byte) error {
	type unmarshaler MailDetailDtoMeasurement
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailDetailDtoMeasurement(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailDetailDtoMeasurement) MarshalJSON() ([]byte, error) {
	type embed MailDetailDtoMeasurement
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailDetailDtoMeasurement) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mailDetailDtoScanFieldUUID     = big.NewInt(1 << 0)
	mailDetailDtoScanFieldStatus   = big.NewInt(1 << 1)
	mailDetailDtoScanFieldCategory = big.NewInt(1 << 2)
	mailDetailDtoScanFieldLabel    = big.NewInt(1 << 3)
)

type MailDetailDtoScan struct {
	// Scan id — fetch it via `/v1/scans/{uuid}`.
	UUID string `json:"uuid" url:"uuid"`
	// `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`.
	Status string `json:"status" url:"status"`
	// `SCAN_REQUEST` or `UNBOXING_REQUEST`.
	Category string `json:"category" url:"category"`
	// Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling.
	Label *string `json:"label,omitempty" url:"label,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailDetailDtoScan) GetUUID() string {
	if m == nil {
		return ""
	}
	return m.UUID
}

func (m *MailDetailDtoScan) GetStatus() string {
	if m == nil {
		return ""
	}
	return m.Status
}

func (m *MailDetailDtoScan) GetCategory() string {
	if m == nil {
		return ""
	}
	return m.Category
}

func (m *MailDetailDtoScan) GetLabel() *string {
	if m == nil {
		return nil
	}
	return m.Label
}

func (m *MailDetailDtoScan) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailDetailDtoScan) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoScan) SetUUID(uuid string) {
	m.UUID = uuid
	m.require(mailDetailDtoScanFieldUUID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoScan) SetStatus(status string) {
	m.Status = status
	m.require(mailDetailDtoScanFieldStatus)
}

// SetCategory sets the Category field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoScan) SetCategory(category string) {
	m.Category = category
	m.require(mailDetailDtoScanFieldCategory)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailDetailDtoScan) SetLabel(label *string) {
	m.Label = label
	m.require(mailDetailDtoScanFieldLabel)
}

func (m *MailDetailDtoScan) UnmarshalJSON(data []byte) error {
	type unmarshaler MailDetailDtoScan
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailDetailDtoScan(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailDetailDtoScan) MarshalJSON() ([]byte, error) {
	type embed MailDetailDtoScan
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailDetailDtoScan) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mailPageDtoFieldData       = big.NewInt(1 << 0)
	mailPageDtoFieldNextCursor = big.NewInt(1 << 1)
	mailPageDtoFieldTotalCount = big.NewInt(1 << 2)
)

type MailPageDto struct {
	Data []*MailPageDtoDataItem `json:"data" url:"data"`
	// Pass as `?cursor=` to fetch the next page. Null on the last page.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Total number of items matching this query across all pages.
	TotalCount int `json:"total_count" url:"total_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailPageDto) GetData() []*MailPageDtoDataItem {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MailPageDto) GetNextCursor() *string {
	if m == nil {
		return nil
	}
	return m.NextCursor
}

func (m *MailPageDto) GetTotalCount() int {
	if m == nil {
		return 0
	}
	return m.TotalCount
}

func (m *MailPageDto) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailPageDto) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDto) SetData(data []*MailPageDtoDataItem) {
	m.Data = data
	m.require(mailPageDtoFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDto) SetNextCursor(nextCursor *string) {
	m.NextCursor = nextCursor
	m.require(mailPageDtoFieldNextCursor)
}

// SetTotalCount sets the TotalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDto) SetTotalCount(totalCount int) {
	m.TotalCount = totalCount
	m.require(mailPageDtoFieldTotalCount)
}

func (m *MailPageDto) UnmarshalJSON(data []byte) error {
	type unmarshaler MailPageDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailPageDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailPageDto) MarshalJSON() ([]byte, error) {
	type embed MailPageDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailPageDto) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mailPageDtoDataItemFieldID               = big.NewInt(1 << 0)
	mailPageDtoDataItemFieldFolderID         = big.NewInt(1 << 1)
	mailPageDtoDataItemFieldIsRead           = big.NewInt(1 << 2)
	mailPageDtoDataItemFieldMailStatus       = big.NewInt(1 << 3)
	mailPageDtoDataItemFieldMailType         = big.NewInt(1 << 4)
	mailPageDtoDataItemFieldSenderName       = big.NewInt(1 << 5)
	mailPageDtoDataItemFieldRecipientName    = big.NewInt(1 << 6)
	mailPageDtoDataItemFieldArrivalDate      = big.NewInt(1 << 7)
	mailPageDtoDataItemFieldEnvelopeImageURL = big.NewInt(1 << 8)
	mailPageDtoDataItemFieldQuarantineReason = big.NewInt(1 << 9)
	mailPageDtoDataItemFieldScan             = big.NewInt(1 << 10)
)

type MailPageDtoDataItem struct {
	// Mail item id (numeric string).
	ID string `json:"id" url:"id"`
	// Id of the folder the item is filed in — see `/v1/folders`.
	FolderID *string `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	IsRead   bool    `json:"is_read" url:"is_read"`
	// Lifecycle status as reported by the mailroom.
	MailStatus    string  `json:"mail_status" url:"mail_status"`
	MailType      string  `json:"mail_type" url:"mail_type"`
	SenderName    *string `json:"sender_name,omitempty" url:"sender_name,omitempty"`
	RecipientName *string `json:"recipient_name,omitempty" url:"recipient_name,omitempty"`
	// When the item arrived at the facility.
	ArrivalDate *time.Time `json:"arrival_date,omitempty" url:"arrival_date,omitempty"`
	// Photo of the item/envelope.
	EnvelopeImageURL *string `json:"envelope_image_url,omitempty" url:"envelope_image_url,omitempty"`
	QuarantineReason *string `json:"quarantine_reason,omitempty" url:"quarantine_reason,omitempty"`
	// The scan requested for this item, when one exists.
	Scan *MailPageDtoDataItemScan `json:"scan,omitempty" url:"scan,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailPageDtoDataItem) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MailPageDtoDataItem) GetFolderID() *string {
	if m == nil {
		return nil
	}
	return m.FolderID
}

func (m *MailPageDtoDataItem) GetIsRead() bool {
	if m == nil {
		return false
	}
	return m.IsRead
}

func (m *MailPageDtoDataItem) GetMailStatus() string {
	if m == nil {
		return ""
	}
	return m.MailStatus
}

func (m *MailPageDtoDataItem) GetMailType() string {
	if m == nil {
		return ""
	}
	return m.MailType
}

func (m *MailPageDtoDataItem) GetSenderName() *string {
	if m == nil {
		return nil
	}
	return m.SenderName
}

func (m *MailPageDtoDataItem) GetRecipientName() *string {
	if m == nil {
		return nil
	}
	return m.RecipientName
}

func (m *MailPageDtoDataItem) GetArrivalDate() *time.Time {
	if m == nil {
		return nil
	}
	return m.ArrivalDate
}

func (m *MailPageDtoDataItem) GetEnvelopeImageURL() *string {
	if m == nil {
		return nil
	}
	return m.EnvelopeImageURL
}

func (m *MailPageDtoDataItem) GetQuarantineReason() *string {
	if m == nil {
		return nil
	}
	return m.QuarantineReason
}

func (m *MailPageDtoDataItem) GetScan() *MailPageDtoDataItemScan {
	if m == nil {
		return nil
	}
	return m.Scan
}

func (m *MailPageDtoDataItem) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailPageDtoDataItem) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetID(id string) {
	m.ID = id
	m.require(mailPageDtoDataItemFieldID)
}

// SetFolderID sets the FolderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetFolderID(folderID *string) {
	m.FolderID = folderID
	m.require(mailPageDtoDataItemFieldFolderID)
}

// SetIsRead sets the IsRead field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetIsRead(isRead bool) {
	m.IsRead = isRead
	m.require(mailPageDtoDataItemFieldIsRead)
}

// SetMailStatus sets the MailStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetMailStatus(mailStatus string) {
	m.MailStatus = mailStatus
	m.require(mailPageDtoDataItemFieldMailStatus)
}

// SetMailType sets the MailType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetMailType(mailType string) {
	m.MailType = mailType
	m.require(mailPageDtoDataItemFieldMailType)
}

// SetSenderName sets the SenderName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetSenderName(senderName *string) {
	m.SenderName = senderName
	m.require(mailPageDtoDataItemFieldSenderName)
}

// SetRecipientName sets the RecipientName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetRecipientName(recipientName *string) {
	m.RecipientName = recipientName
	m.require(mailPageDtoDataItemFieldRecipientName)
}

// SetArrivalDate sets the ArrivalDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetArrivalDate(arrivalDate *time.Time) {
	m.ArrivalDate = arrivalDate
	m.require(mailPageDtoDataItemFieldArrivalDate)
}

// SetEnvelopeImageURL sets the EnvelopeImageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetEnvelopeImageURL(envelopeImageURL *string) {
	m.EnvelopeImageURL = envelopeImageURL
	m.require(mailPageDtoDataItemFieldEnvelopeImageURL)
}

// SetQuarantineReason sets the QuarantineReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetQuarantineReason(quarantineReason *string) {
	m.QuarantineReason = quarantineReason
	m.require(mailPageDtoDataItemFieldQuarantineReason)
}

// SetScan sets the Scan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItem) SetScan(scan *MailPageDtoDataItemScan) {
	m.Scan = scan
	m.require(mailPageDtoDataItemFieldScan)
}

func (m *MailPageDtoDataItem) UnmarshalJSON(data []byte) error {
	type embed MailPageDtoDataItem
	var unmarshaler = struct {
		embed
		ArrivalDate *internal.DateTime `json:"arrival_date,omitempty"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = MailPageDtoDataItem(unmarshaler.embed)
	m.ArrivalDate = unmarshaler.ArrivalDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailPageDtoDataItem) MarshalJSON() ([]byte, error) {
	type embed MailPageDtoDataItem
	var marshaler = struct {
		embed
		ArrivalDate *internal.DateTime `json:"arrival_date,omitempty"`
	}{
		embed:       embed(*m),
		ArrivalDate: internal.NewOptionalDateTime(m.ArrivalDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailPageDtoDataItem) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mailPageDtoDataItemScanFieldUUID     = big.NewInt(1 << 0)
	mailPageDtoDataItemScanFieldStatus   = big.NewInt(1 << 1)
	mailPageDtoDataItemScanFieldCategory = big.NewInt(1 << 2)
	mailPageDtoDataItemScanFieldLabel    = big.NewInt(1 << 3)
)

type MailPageDtoDataItemScan struct {
	// Scan id — fetch it via `/v1/scans/{uuid}`.
	UUID string `json:"uuid" url:"uuid"`
	// `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`.
	Status string `json:"status" url:"status"`
	// `SCAN_REQUEST` or `UNBOXING_REQUEST`.
	Category string `json:"category" url:"category"`
	// Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling.
	Label *string `json:"label,omitempty" url:"label,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailPageDtoDataItemScan) GetUUID() string {
	if m == nil {
		return ""
	}
	return m.UUID
}

func (m *MailPageDtoDataItemScan) GetStatus() string {
	if m == nil {
		return ""
	}
	return m.Status
}

func (m *MailPageDtoDataItemScan) GetCategory() string {
	if m == nil {
		return ""
	}
	return m.Category
}

func (m *MailPageDtoDataItemScan) GetLabel() *string {
	if m == nil {
		return nil
	}
	return m.Label
}

func (m *MailPageDtoDataItemScan) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MailPageDtoDataItemScan) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItemScan) SetUUID(uuid string) {
	m.UUID = uuid
	m.require(mailPageDtoDataItemScanFieldUUID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItemScan) SetStatus(status string) {
	m.Status = status
	m.require(mailPageDtoDataItemScanFieldStatus)
}

// SetCategory sets the Category field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItemScan) SetCategory(category string) {
	m.Category = category
	m.require(mailPageDtoDataItemScanFieldCategory)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailPageDtoDataItemScan) SetLabel(label *string) {
	m.Label = label
	m.require(mailPageDtoDataItemScanFieldLabel)
}

func (m *MailPageDtoDataItemScan) UnmarshalJSON(data []byte) error {
	type unmarshaler MailPageDtoDataItemScan
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailPageDtoDataItemScan(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailPageDtoDataItemScan) MarshalJSON() ([]byte, error) {
	type embed MailPageDtoDataItemScan
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MailPageDtoDataItemScan) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MailsListRequestArrived string

const (
	MailsListRequestArrivedWeek     MailsListRequestArrived = "week"
	MailsListRequestArrivedMonth    MailsListRequestArrived = "month"
	MailsListRequestArrivedHalfYear MailsListRequestArrived = "half_year"
	MailsListRequestArrivedYear     MailsListRequestArrived = "year"
)

func NewMailsListRequestArrivedFromString(s string) (MailsListRequestArrived, error) {
	switch s {
	case "week":
		return MailsListRequestArrivedWeek, nil
	case "month":
		return MailsListRequestArrivedMonth, nil
	case "half_year":
		return MailsListRequestArrivedHalfYear, nil
	case "year":
		return MailsListRequestArrivedYear, nil
	}
	var t MailsListRequestArrived
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailsListRequestArrived) Ptr() *MailsListRequestArrived {
	return &m
}

type MailsListRequestIsRead string

const (
	MailsListRequestIsReadTrue  MailsListRequestIsRead = "true"
	MailsListRequestIsReadFalse MailsListRequestIsRead = "false"
)

func NewMailsListRequestIsReadFromString(s string) (MailsListRequestIsRead, error) {
	switch s {
	case "true":
		return MailsListRequestIsReadTrue, nil
	case "false":
		return MailsListRequestIsReadFalse, nil
	}
	var t MailsListRequestIsRead
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailsListRequestIsRead) Ptr() *MailsListRequestIsRead {
	return &m
}

type MailsListRequestMailTypeItem string

const (
	MailsListRequestMailTypeItemLetter       MailsListRequestMailTypeItem = "letter"
	MailsListRequestMailTypeItemLargeLetter  MailsListRequestMailTypeItem = "large_letter"
	MailsListRequestMailTypeItemMagazine     MailsListRequestMailTypeItem = "magazine"
	MailsListRequestMailTypeItemPackage      MailsListRequestMailTypeItem = "package"
	MailsListRequestMailTypeItemSoftpak      MailsListRequestMailTypeItem = "softpak"
	MailsListRequestMailTypeItemCatalog      MailsListRequestMailTypeItem = "catalog"
	MailsListRequestMailTypeItemDistribution MailsListRequestMailTypeItem = "distribution"
	MailsListRequestMailTypeItemFulfillment  MailsListRequestMailTypeItem = "fulfillment"
	MailsListRequestMailTypeItemInventory    MailsListRequestMailTypeItem = "inventory"
)

func NewMailsListRequestMailTypeItemFromString(s string) (MailsListRequestMailTypeItem, error) {
	switch s {
	case "letter":
		return MailsListRequestMailTypeItemLetter, nil
	case "large_letter":
		return MailsListRequestMailTypeItemLargeLetter, nil
	case "magazine":
		return MailsListRequestMailTypeItemMagazine, nil
	case "package":
		return MailsListRequestMailTypeItemPackage, nil
	case "softpak":
		return MailsListRequestMailTypeItemSoftpak, nil
	case "catalog":
		return MailsListRequestMailTypeItemCatalog, nil
	case "distribution":
		return MailsListRequestMailTypeItemDistribution, nil
	case "fulfillment":
		return MailsListRequestMailTypeItemFulfillment, nil
	case "inventory":
		return MailsListRequestMailTypeItemInventory, nil
	}
	var t MailsListRequestMailTypeItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailsListRequestMailTypeItem) Ptr() *MailsListRequestMailTypeItem {
	return &m
}

type MailsListRequestScanStatusItem string

const (
	MailsListRequestScanStatusItemInProcess MailsListRequestScanStatusItem = "in_process"
	MailsListRequestScanStatusItemCancelled MailsListRequestScanStatusItem = "cancelled"
	MailsListRequestScanStatusItemRejected  MailsListRequestScanStatusItem = "rejected"
	MailsListRequestScanStatusItemCompleted MailsListRequestScanStatusItem = "completed"
	MailsListRequestScanStatusItemDeleted   MailsListRequestScanStatusItem = "deleted"
	MailsListRequestScanStatusItemRestoring MailsListRequestScanStatusItem = "restoring"
	MailsListRequestScanStatusItemNone      MailsListRequestScanStatusItem = "none"
)

func NewMailsListRequestScanStatusItemFromString(s string) (MailsListRequestScanStatusItem, error) {
	switch s {
	case "in_process":
		return MailsListRequestScanStatusItemInProcess, nil
	case "cancelled":
		return MailsListRequestScanStatusItemCancelled, nil
	case "rejected":
		return MailsListRequestScanStatusItemRejected, nil
	case "completed":
		return MailsListRequestScanStatusItemCompleted, nil
	case "deleted":
		return MailsListRequestScanStatusItemDeleted, nil
	case "restoring":
		return MailsListRequestScanStatusItemRestoring, nil
	case "none":
		return MailsListRequestScanStatusItemNone, nil
	}
	var t MailsListRequestScanStatusItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailsListRequestScanStatusItem) Ptr() *MailsListRequestScanStatusItem {
	return &m
}

type MailsListRequestSort string

const (
	MailsListRequestSortNewest MailsListRequestSort = "newest"
	MailsListRequestSortOldest MailsListRequestSort = "oldest"
)

func NewMailsListRequestSortFromString(s string) (MailsListRequestSort, error) {
	switch s {
	case "newest":
		return MailsListRequestSortNewest, nil
	case "oldest":
		return MailsListRequestSortOldest, nil
	}
	var t MailsListRequestSort
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailsListRequestSort) Ptr() *MailsListRequestSort {
	return &m
}

type MailsListRequestStatusItem string

const (
	MailsListRequestStatusItemInbox          MailsListRequestStatusItem = "inbox"
	MailsListRequestStatusItemArchived       MailsListRequestStatusItem = "archived"
	MailsListRequestStatusItemQuarantine     MailsListRequestStatusItem = "quarantine"
	MailsListRequestStatusItemDiscardRequest MailsListRequestStatusItem = "discard_request"
)

func NewMailsListRequestStatusItemFromString(s string) (MailsListRequestStatusItem, error) {
	switch s {
	case "inbox":
		return MailsListRequestStatusItemInbox, nil
	case "archived":
		return MailsListRequestStatusItemArchived, nil
	case "quarantine":
		return MailsListRequestStatusItemQuarantine, nil
	case "discard_request":
		return MailsListRequestStatusItemDiscardRequest, nil
	}
	var t MailsListRequestStatusItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailsListRequestStatusItem) Ptr() *MailsListRequestStatusItem {
	return &m
}

var (
	mailsUnarchiveRequestFieldID = big.NewInt(1 << 0)
)

type MailsUnarchiveRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MailsUnarchiveRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsUnarchiveRequest) SetID(id string) {
	m.ID = id
	m.require(mailsUnarchiveRequestFieldID)
}

var (
	mailsUndiscardRequestFieldID = big.NewInt(1 << 0)
)

type MailsUndiscardRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MailsUndiscardRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MailsUndiscardRequest) SetID(id string) {
	m.ID = id
	m.require(mailsUndiscardRequestFieldID)
}

var (
	updateMailDtoFieldID       = big.NewInt(1 << 0)
	updateMailDtoFieldIsRead   = big.NewInt(1 << 1)
	updateMailDtoFieldFolderID = big.NewInt(1 << 2)
)

type UpdateMailDto struct {
	ID     string `json:"-" url:"-"`
	IsRead *bool  `json:"is_read,omitempty" url:"-"`
	// Move the item to this folder. Pass null to remove it from its folder.
	FolderID *string `json:"folder_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateMailDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMailDto) SetID(id string) {
	u.ID = id
	u.require(updateMailDtoFieldID)
}

// SetIsRead sets the IsRead field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMailDto) SetIsRead(isRead *bool) {
	u.IsRead = isRead
	u.require(updateMailDtoFieldIsRead)
}

// SetFolderID sets the FolderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMailDto) SetFolderID(folderID *string) {
	u.FolderID = folderID
	u.require(updateMailDtoFieldFolderID)
}

func (u *UpdateMailDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMailDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateMailDto(body)
	return nil
}

func (u *UpdateMailDto) MarshalJSON() ([]byte, error) {
	type embed UpdateMailDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
