// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
)

var (
	completeSandboxScanDtoFieldID      = big.NewInt(1 << 0)
	completeSandboxScanDtoFieldLabel   = big.NewInt(1 << 1)
	completeSandboxScanDtoFieldSummary = big.NewInt(1 << 2)
)

type CompleteSandboxScanDto struct {
	ID string `json:"-" url:"-"`
	// Short document label the AI would produce, e.g. "Insurance". Set on the scan.
	Label *string `json:"label,omitempty" url:"-"`
	// Summary bullet points; retrievable via `GET /v1/scans/{id}/summary`.
	Summary []string `json:"summary,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CompleteSandboxScanDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompleteSandboxScanDto) SetID(id string) {
	c.ID = id
	c.require(completeSandboxScanDtoFieldID)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompleteSandboxScanDto) SetLabel(label *string) {
	c.Label = label
	c.require(completeSandboxScanDtoFieldLabel)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompleteSandboxScanDto) SetSummary(summary []string) {
	c.Summary = summary
	c.require(completeSandboxScanDtoFieldSummary)
}

func (c *CompleteSandboxScanDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CompleteSandboxScanDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CompleteSandboxScanDto(body)
	return nil
}

func (c *CompleteSandboxScanDto) MarshalJSON() ([]byte, error) {
	type embed CompleteSandboxScanDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	seedSandboxMailDtoFieldSenderName  = big.NewInt(1 << 0)
	seedSandboxMailDtoFieldMailType    = big.NewInt(1 << 1)
	seedSandboxMailDtoFieldWeight      = big.NewInt(1 << 2)
	seedSandboxMailDtoFieldMeasurement = big.NewInt(1 << 3)
)

type SeedSandboxMailDto struct {
	SenderName *string `json:"sender_name,omitempty" url:"-"`
	// Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`.
	MailType *SeedSandboxMailDtoMailType `json:"mail_type,omitempty" url:"-"`
	// Item weight, in pounds.
	Weight *float64 `json:"weight,omitempty" url:"-"`
	// Item dimensions, in inches.
	Measurement *SeedSandboxMailDtoMeasurement `json:"measurement,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SeedSandboxMailDto) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSenderName sets the SenderName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDto) SetSenderName(senderName *string) {
	s.SenderName = senderName
	s.require(seedSandboxMailDtoFieldSenderName)
}

// SetMailType sets the MailType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDto) SetMailType(mailType *SeedSandboxMailDtoMailType) {
	s.MailType = mailType
	s.require(seedSandboxMailDtoFieldMailType)
}

// SetWeight sets the Weight field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDto) SetWeight(weight *float64) {
	s.Weight = weight
	s.require(seedSandboxMailDtoFieldWeight)
}

// SetMeasurement sets the Measurement field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDto) SetMeasurement(measurement *SeedSandboxMailDtoMeasurement) {
	s.Measurement = measurement
	s.require(seedSandboxMailDtoFieldMeasurement)
}

func (s *SeedSandboxMailDto) UnmarshalJSON(data []byte) error {
	type unmarshaler SeedSandboxMailDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SeedSandboxMailDto(body)
	return nil
}

func (s *SeedSandboxMailDto) MarshalJSON() ([]byte, error) {
	type embed SeedSandboxMailDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	seedMailResultDtoFieldMailID = big.NewInt(1 << 0)
)

type SeedMailResultDto struct {
	// Id of the seeded mail item (numeric string).
	MailID string `json:"mail_id" url:"mail_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SeedMailResultDto) GetMailID() string {
	if s == nil {
		return ""
	}
	return s.MailID
}

func (s *SeedMailResultDto) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SeedMailResultDto) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMailID sets the MailID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedMailResultDto) SetMailID(mailID string) {
	s.MailID = mailID
	s.require(seedMailResultDtoFieldMailID)
}

func (s *SeedMailResultDto) UnmarshalJSON(data []byte) error {
	type unmarshaler SeedMailResultDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SeedMailResultDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SeedMailResultDto) MarshalJSON() ([]byte, error) {
	type embed SeedMailResultDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SeedMailResultDto) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	seedResultDtoFieldMailIDs = big.NewInt(1 << 0)
)

type SeedResultDto struct {
	// Ids of the seeded mail items (numeric strings).
	MailIDs []string `json:"mail_ids" url:"mail_ids"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SeedResultDto) GetMailIDs() []string {
	if s == nil {
		return nil
	}
	return s.MailIDs
}

func (s *SeedResultDto) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SeedResultDto) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMailIDs sets the MailIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedResultDto) SetMailIDs(mailIDs []string) {
	s.MailIDs = mailIDs
	s.require(seedResultDtoFieldMailIDs)
}

func (s *SeedResultDto) UnmarshalJSON(data []byte) error {
	type unmarshaler SeedResultDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SeedResultDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SeedResultDto) MarshalJSON() ([]byte, error) {
	type embed SeedResultDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SeedResultDto) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Type of the seeded item. `LETTER` and `LARGELETTER` accept a `SCAN_REQUEST`; the rest accept an `UNBOXING_REQUEST`.
type SeedSandboxMailDtoMailType string

const (
	SeedSandboxMailDtoMailTypeLetter      SeedSandboxMailDtoMailType = "LETTER"
	SeedSandboxMailDtoMailTypeLargeletter SeedSandboxMailDtoMailType = "LARGELETTER"
	SeedSandboxMailDtoMailTypeMagazine    SeedSandboxMailDtoMailType = "MAGAZINE"
	SeedSandboxMailDtoMailTypeCatalog     SeedSandboxMailDtoMailType = "CATALOG"
	SeedSandboxMailDtoMailTypeSoftpak     SeedSandboxMailDtoMailType = "SOFTPAK"
	SeedSandboxMailDtoMailTypePackage     SeedSandboxMailDtoMailType = "PACKAGE"
)

func NewSeedSandboxMailDtoMailTypeFromString(s string) (SeedSandboxMailDtoMailType, error) {
	switch s {
	case "LETTER":
		return SeedSandboxMailDtoMailTypeLetter, nil
	case "LARGELETTER":
		return SeedSandboxMailDtoMailTypeLargeletter, nil
	case "MAGAZINE":
		return SeedSandboxMailDtoMailTypeMagazine, nil
	case "CATALOG":
		return SeedSandboxMailDtoMailTypeCatalog, nil
	case "SOFTPAK":
		return SeedSandboxMailDtoMailTypeSoftpak, nil
	case "PACKAGE":
		return SeedSandboxMailDtoMailTypePackage, nil
	}
	var t SeedSandboxMailDtoMailType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SeedSandboxMailDtoMailType) Ptr() *SeedSandboxMailDtoMailType {
	return &s
}

// Item dimensions, in inches.
var (
	seedSandboxMailDtoMeasurementFieldWidth  = big.NewInt(1 << 0)
	seedSandboxMailDtoMeasurementFieldHeight = big.NewInt(1 << 1)
	seedSandboxMailDtoMeasurementFieldLength = big.NewInt(1 << 2)
)

type SeedSandboxMailDtoMeasurement struct {
	// Inches.
	Width float64 `json:"width" url:"width"`
	// Inches.
	Height float64 `json:"height" url:"height"`
	// Inches.
	Length float64 `json:"length" url:"length"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SeedSandboxMailDtoMeasurement) GetWidth() float64 {
	if s == nil {
		return 0
	}
	return s.Width
}

func (s *SeedSandboxMailDtoMeasurement) GetHeight() float64 {
	if s == nil {
		return 0
	}
	return s.Height
}

func (s *SeedSandboxMailDtoMeasurement) GetLength() float64 {
	if s == nil {
		return 0
	}
	return s.Length
}

func (s *SeedSandboxMailDtoMeasurement) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SeedSandboxMailDtoMeasurement) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetWidth sets the Width field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDtoMeasurement) SetWidth(width float64) {
	s.Width = width
	s.require(seedSandboxMailDtoMeasurementFieldWidth)
}

// SetHeight sets the Height field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDtoMeasurement) SetHeight(height float64) {
	s.Height = height
	s.require(seedSandboxMailDtoMeasurementFieldHeight)
}

// SetLength sets the Length field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SeedSandboxMailDtoMeasurement) SetLength(length float64) {
	s.Length = length
	s.require(seedSandboxMailDtoMeasurementFieldLength)
}

func (s *SeedSandboxMailDtoMeasurement) UnmarshalJSON(data []byte) error {
	type unmarshaler SeedSandboxMailDtoMeasurement
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SeedSandboxMailDtoMeasurement(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SeedSandboxMailDtoMeasurement) MarshalJSON() ([]byte, error) {
	type embed SeedSandboxMailDtoMeasurement
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SeedSandboxMailDtoMeasurement) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
