// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCompleteSandboxScanDto(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &CompleteSandboxScanDto{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLabel", func(t *testing.T) {
		obj := &CompleteSandboxScanDto{}
		var fernTestValueLabel *string
		obj.SetLabel(fernTestValueLabel)
		assert.Equal(t, fernTestValueLabel, obj.Label)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSummary", func(t *testing.T) {
		obj := &CompleteSandboxScanDto{}
		var fernTestValueSummary []string
		obj.SetSummary(fernTestValueSummary)
		assert.Equal(t, fernTestValueSummary, obj.Summary)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCompleteSandboxScanDto(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompleteSandboxScanDto{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLabel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompleteSandboxScanDto{}
		var fernTestValueLabel *string

		// Act
		obj.SetLabel(fernTestValueLabel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSummary_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompleteSandboxScanDto{}
		var fernTestValueSummary []string

		// Act
		obj.SetSummary(fernTestValueSummary)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSeedSandboxMailDto(t *testing.T) {
	t.Run("SetSenderName", func(t *testing.T) {
		obj := &SeedSandboxMailDto{}
		var fernTestValueSenderName *string
		obj.SetSenderName(fernTestValueSenderName)
		assert.Equal(t, fernTestValueSenderName, obj.SenderName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMailType", func(t *testing.T) {
		obj := &SeedSandboxMailDto{}
		var fernTestValueMailType *SeedSandboxMailDtoMailType
		obj.SetMailType(fernTestValueMailType)
		assert.Equal(t, fernTestValueMailType, obj.MailType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWeight", func(t *testing.T) {
		obj := &SeedSandboxMailDto{}
		var fernTestValueWeight *float64
		obj.SetWeight(fernTestValueWeight)
		assert.Equal(t, fernTestValueWeight, obj.Weight)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeasurement", func(t *testing.T) {
		obj := &SeedSandboxMailDto{}
		var fernTestValueMeasurement *SeedSandboxMailDtoMeasurement
		obj.SetMeasurement(fernTestValueMeasurement)
		assert.Equal(t, fernTestValueMeasurement, obj.Measurement)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSeedSandboxMailDto(t *testing.T) {
	t.Run("SetSenderName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDto{}
		var fernTestValueSenderName *string

		// Act
		obj.SetSenderName(fernTestValueSenderName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMailType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDto{}
		var fernTestValueMailType *SeedSandboxMailDtoMailType

		// Act
		obj.SetMailType(fernTestValueMailType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWeight_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDto{}
		var fernTestValueWeight *float64

		// Act
		obj.SetWeight(fernTestValueWeight)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeasurement_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDto{}
		var fernTestValueMeasurement *SeedSandboxMailDtoMeasurement

		// Act
		obj.SetMeasurement(fernTestValueMeasurement)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSeedMailResultDto(t *testing.T) {
	t.Run("SetMailID", func(t *testing.T) {
		obj := &SeedMailResultDto{}
		var fernTestValueMailID string
		obj.SetMailID(fernTestValueMailID)
		assert.Equal(t, fernTestValueMailID, obj.MailID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSeedMailResultDto(t *testing.T) {
	t.Run("GetMailID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedMailResultDto{}
		var expected string
		obj.MailID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMailID(), "getter should return the property value")
	})

	t.Run("GetMailID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedMailResultDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMailID() // Should return zero value
	})

}

func TestSettersMarkExplicitSeedMailResultDto(t *testing.T) {
	t.Run("SetMailID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedMailResultDto{}
		var fernTestValueMailID string

		// Act
		obj.SetMailID(fernTestValueMailID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSeedResultDto(t *testing.T) {
	t.Run("SetMailIDs", func(t *testing.T) {
		obj := &SeedResultDto{}
		var fernTestValueMailIDs []string
		obj.SetMailIDs(fernTestValueMailIDs)
		assert.Equal(t, fernTestValueMailIDs, obj.MailIDs)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSeedResultDto(t *testing.T) {
	t.Run("GetMailIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedResultDto{}
		var expected []string
		obj.MailIDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMailIDs(), "getter should return the property value")
	})

	t.Run("GetMailIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedResultDto{}
		obj.MailIDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetMailIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetMailIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedResultDto
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMailIDs() // Should return zero value
	})

}

func TestSettersMarkExplicitSeedResultDto(t *testing.T) {
	t.Run("SetMailIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedResultDto{}
		var fernTestValueMailIDs []string

		// Act
		obj.SetMailIDs(fernTestValueMailIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSeedSandboxMailDtoMeasurement(t *testing.T) {
	t.Run("SetWidth", func(t *testing.T) {
		obj := &SeedSandboxMailDtoMeasurement{}
		var fernTestValueWidth float64
		obj.SetWidth(fernTestValueWidth)
		assert.Equal(t, fernTestValueWidth, obj.Width)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeight", func(t *testing.T) {
		obj := &SeedSandboxMailDtoMeasurement{}
		var fernTestValueHeight float64
		obj.SetHeight(fernTestValueHeight)
		assert.Equal(t, fernTestValueHeight, obj.Height)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLength", func(t *testing.T) {
		obj := &SeedSandboxMailDtoMeasurement{}
		var fernTestValueLength float64
		obj.SetLength(fernTestValueLength)
		assert.Equal(t, fernTestValueLength, obj.Length)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSeedSandboxMailDtoMeasurement(t *testing.T) {
	t.Run("GetWidth", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}
		var expected float64
		obj.Width = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWidth(), "getter should return the property value")
	})

	t.Run("GetWidth_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedSandboxMailDtoMeasurement
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWidth() // Should return zero value
	})

	t.Run("GetHeight", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}
		var expected float64
		obj.Height = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeight(), "getter should return the property value")
	})

	t.Run("GetHeight_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedSandboxMailDtoMeasurement
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeight() // Should return zero value
	})

	t.Run("GetLength", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}
		var expected float64
		obj.Length = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLength(), "getter should return the property value")
	})

	t.Run("GetLength_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedSandboxMailDtoMeasurement
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLength() // Should return zero value
	})

}

func TestSettersMarkExplicitSeedSandboxMailDtoMeasurement(t *testing.T) {
	t.Run("SetWidth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}
		var fernTestValueWidth float64

		// Act
		obj.SetWidth(fernTestValueWidth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeight_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}
		var fernTestValueHeight float64

		// Act
		obj.SetHeight(fernTestValueHeight)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLength_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}
		var fernTestValueLength float64

		// Act
		obj.SetLength(fernTestValueLength)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingSeedMailResultDto(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedMailResultDto{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SeedMailResultDto
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SeedMailResultDto
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SeedMailResultDto
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSeedResultDto(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedResultDto{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SeedResultDto
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SeedResultDto
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SeedResultDto
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSeedSandboxMailDtoMeasurement(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SeedSandboxMailDtoMeasurement{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SeedSandboxMailDtoMeasurement
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SeedSandboxMailDtoMeasurement
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SeedSandboxMailDtoMeasurement
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringSeedMailResultDto(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SeedMailResultDto{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedMailResultDto
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSeedResultDto(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SeedResultDto{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedResultDto
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSeedSandboxMailDtoMeasurement(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SeedSandboxMailDtoMeasurement{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedSandboxMailDtoMeasurement
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumSeedSandboxMailDtoMailType(t *testing.T) {
	t.Run("NewFromString_LETTER", func(t *testing.T) {
		t.Parallel()
		val, err := NewSeedSandboxMailDtoMailTypeFromString("LETTER")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SeedSandboxMailDtoMailType("LETTER"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_LARGELETTER", func(t *testing.T) {
		t.Parallel()
		val, err := NewSeedSandboxMailDtoMailTypeFromString("LARGELETTER")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SeedSandboxMailDtoMailType("LARGELETTER"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_MAGAZINE", func(t *testing.T) {
		t.Parallel()
		val, err := NewSeedSandboxMailDtoMailTypeFromString("MAGAZINE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SeedSandboxMailDtoMailType("MAGAZINE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_CATALOG", func(t *testing.T) {
		t.Parallel()
		val, err := NewSeedSandboxMailDtoMailTypeFromString("CATALOG")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SeedSandboxMailDtoMailType("CATALOG"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_SOFTPAK", func(t *testing.T) {
		t.Parallel()
		val, err := NewSeedSandboxMailDtoMailTypeFromString("SOFTPAK")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SeedSandboxMailDtoMailType("SOFTPAK"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_PACKAGE", func(t *testing.T) {
		t.Parallel()
		val, err := NewSeedSandboxMailDtoMailTypeFromString("PACKAGE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SeedSandboxMailDtoMailType("PACKAGE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewSeedSandboxMailDtoMailTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewSeedSandboxMailDtoMailTypeFromString("LETTER")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesSeedMailResultDto(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SeedMailResultDto{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedMailResultDto
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSeedResultDto(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SeedResultDto{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedResultDto
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSeedSandboxMailDtoMeasurement(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SeedSandboxMailDtoMeasurement{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SeedSandboxMailDtoMeasurement
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
