// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
	time "time"
)

var (
	shipmentsGetRequestFieldID = big.NewInt(1 << 0)
)

type ShipmentsGetRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShipmentsGetRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentsGetRequest) SetID(id string) {
	s.ID = id
	s.require(shipmentsGetRequestFieldID)
}

var (
	shipmentsListRequestFieldLimit  = big.NewInt(1 << 0)
	shipmentsListRequestFieldCursor = big.NewInt(1 << 1)
	shipmentsListRequestFieldType   = big.NewInt(1 << 2)
	shipmentsListRequestFieldStatus = big.NewInt(1 << 3)
)

type ShipmentsListRequest struct {
	// Page size, capped at 100.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor — the `next_cursor` of the previous response. Omit for the first page.
	Cursor *string                           `json:"-" url:"cursor,omitempty"`
	Type   []*ShipmentsListRequestTypeItem   `json:"-" url:"type,omitempty"`
	Status []*ShipmentsListRequestStatusItem `json:"-" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *ShipmentsListRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentsListRequest) SetLimit(limit *int) {
	s.Limit = limit
	s.require(shipmentsListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentsListRequest) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(shipmentsListRequestFieldCursor)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentsListRequest) SetType(type_ []*ShipmentsListRequestTypeItem) {
	s.Type = type_
	s.require(shipmentsListRequestFieldType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentsListRequest) SetStatus(status []*ShipmentsListRequestStatusItem) {
	s.Status = status
	s.require(shipmentsListRequestFieldStatus)
}

var (
	shipmentDetailDtoFieldID                          = big.NewInt(1 << 0)
	shipmentDetailDtoFieldType                        = big.NewInt(1 << 1)
	shipmentDetailDtoFieldStatus                      = big.NewInt(1 << 2)
	shipmentDetailDtoFieldTrackingNumber              = big.NewInt(1 << 3)
	shipmentDetailDtoFieldServiceName                 = big.NewInt(1 << 4)
	shipmentDetailDtoFieldDestination                 = big.NewInt(1 << 5)
	shipmentDetailDtoFieldItemCount                   = big.NewInt(1 << 6)
	shipmentDetailDtoFieldRequestedShipDate           = big.NewInt(1 << 7)
	shipmentDetailDtoFieldCreatedOn                   = big.NewInt(1 << 8)
	shipmentDetailDtoFieldDepositCheckSlipCompanyName = big.NewInt(1 << 9)
	shipmentDetailDtoFieldInstructions                = big.NewInt(1 << 10)
	shipmentDetailDtoFieldIsExpedited                 = big.NewInt(1 << 11)
	shipmentDetailDtoFieldIsInsured                   = big.NewInt(1 << 12)
	shipmentDetailDtoFieldInsuredAmount               = big.NewInt(1 << 13)
	shipmentDetailDtoFieldDeclaredValue               = big.NewInt(1 << 14)
	shipmentDetailDtoFieldRejectReason                = big.NewInt(1 << 15)
	shipmentDetailDtoFieldMailItems                   = big.NewInt(1 << 16)
)

type ShipmentDetailDto struct {
	// Shipment id (UUID).
	ID   string                `json:"id" url:"id"`
	Type ShipmentDetailDtoType `json:"type" url:"type"`
	// Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment.
	Status ShipmentDetailDtoStatus `json:"status" url:"status"`
	// Carrier tracking number, once the shipment is on its way.
	TrackingNumber *string `json:"tracking_number,omitempty" url:"tracking_number,omitempty"`
	// Carrier service used (e.g. "FedEx International Priority").
	ServiceName *string `json:"service_name,omitempty" url:"service_name,omitempty"`
	// Where it ships to. Only present for `shipment` and `check_deposit` types — returns go back to the sender and pickups happen at the facility.
	Destination *ShipmentDetailDtoDestination `json:"destination,omitempty" url:"destination,omitempty"`
	// Number of mail items packed into the request.
	ItemCount int `json:"item_count" url:"item_count"`
	// The ship-out date the customer asked for.
	RequestedShipDate *time.Time `json:"requested_ship_date,omitempty" url:"requested_ship_date,omitempty"`
	// When the request was made.
	CreatedOn time.Time `json:"created_on" url:"created_on"`
	// `check_deposit` only.
	DepositCheckSlipCompanyName *string `json:"deposit_check_slip_company_name,omitempty" url:"deposit_check_slip_company_name,omitempty"`
	// Packing instructions given when the request was made.
	Instructions *string `json:"instructions,omitempty" url:"instructions,omitempty"`
	IsExpedited  bool    `json:"is_expedited" url:"is_expedited"`
	IsInsured    bool    `json:"is_insured" url:"is_insured"`
	// Insured value in USD. Null when the shipment is not insured.
	InsuredAmount *float64 `json:"insured_amount,omitempty" url:"insured_amount,omitempty"`
	// Total declared customs value of the packed items, in USD.
	DeclaredValue float64 `json:"declared_value" url:"declared_value"`
	// Why the request was rejected. Null unless `status` is `rejected`.
	RejectReason *string                           `json:"reject_reason,omitempty" url:"reject_reason,omitempty"`
	MailItems    []*ShipmentDetailDtoMailItemsItem `json:"mail_items" url:"mail_items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShipmentDetailDto) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ShipmentDetailDto) GetType() ShipmentDetailDtoType {
	if s == nil {
		return ""
	}
	return s.Type
}

func (s *ShipmentDetailDto) GetStatus() ShipmentDetailDtoStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShipmentDetailDto) GetTrackingNumber() *string {
	if s == nil {
		return nil
	}
	return s.TrackingNumber
}

func (s *ShipmentDetailDto) GetServiceName() *string {
	if s == nil {
		return nil
	}
	return s.ServiceName
}

func (s *ShipmentDetailDto) GetDestination() *ShipmentDetailDtoDestination {
	if s == nil {
		return nil
	}
	return s.Destination
}

func (s *ShipmentDetailDto) GetItemCount() int {
	if s == nil {
		return 0
	}
	return s.ItemCount
}

func (s *ShipmentDetailDto) GetRequestedShipDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.RequestedShipDate
}

func (s *ShipmentDetailDto) GetCreatedOn() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedOn
}

func (s *ShipmentDetailDto) GetDepositCheckSlipCompanyName() *string {
	if s == nil {
		return nil
	}
	return s.DepositCheckSlipCompanyName
}

func (s *ShipmentDetailDto) GetInstructions() *string {
	if s == nil {
		return nil
	}
	return s.Instructions
}

func (s *ShipmentDetailDto) GetIsExpedited() bool {
	if s == nil {
		return false
	}
	return s.IsExpedited
}

func (s *ShipmentDetailDto) GetIsInsured() bool {
	if s == nil {
		return false
	}
	return s.IsInsured
}

func (s *ShipmentDetailDto) GetInsuredAmount() *float64 {
	if s == nil {
		return nil
	}
	return s.InsuredAmount
}

func (s *ShipmentDetailDto) GetDeclaredValue() float64 {
	if s == nil {
		return 0
	}
	return s.DeclaredValue
}

func (s *ShipmentDetailDto) GetRejectReason() *string {
	if s == nil {
		return nil
	}
	return s.RejectReason
}

func (s *ShipmentDetailDto) GetMailItems() []*ShipmentDetailDtoMailItemsItem {
	if s == nil {
		return nil
	}
	return s.MailItems
}

func (s *ShipmentDetailDto) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ShipmentDetailDto) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetID(id string) {
	s.ID = id
	s.require(shipmentDetailDtoFieldID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetType(type_ ShipmentDetailDtoType) {
	s.Type = type_
	s.require(shipmentDetailDtoFieldType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetStatus(status ShipmentDetailDtoStatus) {
	s.Status = status
	s.require(shipmentDetailDtoFieldStatus)
}

// SetTrackingNumber sets the TrackingNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetTrackingNumber(trackingNumber *string) {
	s.TrackingNumber = trackingNumber
	s.require(shipmentDetailDtoFieldTrackingNumber)
}

// SetServiceName sets the ServiceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetServiceName(serviceName *string) {
	s.ServiceName = serviceName
	s.require(shipmentDetailDtoFieldServiceName)
}

// SetDestination sets the Destination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetDestination(destination *ShipmentDetailDtoDestination) {
	s.Destination = destination
	s.require(shipmentDetailDtoFieldDestination)
}

// SetItemCount sets the ItemCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetItemCount(itemCount int) {
	s.ItemCount = itemCount
	s.require(shipmentDetailDtoFieldItemCount)
}

// SetRequestedShipDate sets the RequestedShipDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetRequestedShipDate(requestedShipDate *time.Time) {
	s.RequestedShipDate = requestedShipDate
	s.require(shipmentDetailDtoFieldRequestedShipDate)
}

// SetCreatedOn sets the CreatedOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetCreatedOn(createdOn time.Time) {
	s.CreatedOn = createdOn
	s.require(shipmentDetailDtoFieldCreatedOn)
}

// SetDepositCheckSlipCompanyName sets the DepositCheckSlipCompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetDepositCheckSlipCompanyName(depositCheckSlipCompanyName *string) {
	s.DepositCheckSlipCompanyName = depositCheckSlipCompanyName
	s.require(shipmentDetailDtoFieldDepositCheckSlipCompanyName)
}

// SetInstructions sets the Instructions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetInstructions(instructions *string) {
	s.Instructions = instructions
	s.require(shipmentDetailDtoFieldInstructions)
}

// SetIsExpedited sets the IsExpedited field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetIsExpedited(isExpedited bool) {
	s.IsExpedited = isExpedited
	s.require(shipmentDetailDtoFieldIsExpedited)
}

// SetIsInsured sets the IsInsured field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetIsInsured(isInsured bool) {
	s.IsInsured = isInsured
	s.require(shipmentDetailDtoFieldIsInsured)
}

// SetInsuredAmount sets the InsuredAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetInsuredAmount(insuredAmount *float64) {
	s.InsuredAmount = insuredAmount
	s.require(shipmentDetailDtoFieldInsuredAmount)
}

// SetDeclaredValue sets the DeclaredValue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetDeclaredValue(declaredValue float64) {
	s.DeclaredValue = declaredValue
	s.require(shipmentDetailDtoFieldDeclaredValue)
}

// SetRejectReason sets the RejectReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetRejectReason(rejectReason *string) {
	s.RejectReason = rejectReason
	s.require(shipmentDetailDtoFieldRejectReason)
}

// SetMailItems sets the MailItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDto) SetMailItems(mailItems []*ShipmentDetailDtoMailItemsItem) {
	s.MailItems = mailItems
	s.require(shipmentDetailDtoFieldMailItems)
}

func (s *ShipmentDetailDto) UnmarshalJSON(data []byte) error {
	type embed ShipmentDetailDto
	var unmarshaler = struct {
		embed
		RequestedShipDate *internal.DateTime `json:"requested_ship_date,omitempty"`
		CreatedOn         *internal.DateTime `json:"created_on"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = ShipmentDetailDto(unmarshaler.embed)
	s.RequestedShipDate = unmarshaler.RequestedShipDate.TimePtr()
	s.CreatedOn = unmarshaler.CreatedOn.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShipmentDetailDto) MarshalJSON() ([]byte, error) {
	type embed ShipmentDetailDto
	var marshaler = struct {
		embed
		RequestedShipDate *internal.DateTime `json:"requested_ship_date,omitempty"`
		CreatedOn         *internal.DateTime `json:"created_on"`
	}{
		embed:             embed(*s),
		RequestedShipDate: internal.NewOptionalDateTime(s.RequestedShipDate),
		CreatedOn:         internal.NewDateTime(s.CreatedOn),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShipmentDetailDto) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	shipmentDetailDtoDestinationFieldName       = big.NewInt(1 << 0)
	shipmentDetailDtoDestinationFieldLine1      = big.NewInt(1 << 1)
	shipmentDetailDtoDestinationFieldLine2      = big.NewInt(1 << 2)
	shipmentDetailDtoDestinationFieldCity       = big.NewInt(1 << 3)
	shipmentDetailDtoDestinationFieldState      = big.NewInt(1 << 4)
	shipmentDetailDtoDestinationFieldPostalCode = big.NewInt(1 << 5)
	shipmentDetailDtoDestinationFieldCountry    = big.NewInt(1 << 6)
)

type ShipmentDetailDtoDestination struct {
	// Recipient name on the address.
	Name       *string `json:"name,omitempty" url:"name,omitempty"`
	Line1      *string `json:"line1,omitempty" url:"line1,omitempty"`
	Line2      *string `json:"line2,omitempty" url:"line2,omitempty"`
	City       *string `json:"city,omitempty" url:"city,omitempty"`
	State      *string `json:"state,omitempty" url:"state,omitempty"`
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	Country    *string `json:"country,omitempty" url:"country,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShipmentDetailDtoDestination) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ShipmentDetailDtoDestination) GetLine1() *string {
	if s == nil {
		return nil
	}
	return s.Line1
}

func (s *ShipmentDetailDtoDestination) GetLine2() *string {
	if s == nil {
		return nil
	}
	return s.Line2
}

func (s *ShipmentDetailDtoDestination) GetCity() *string {
	if s == nil {
		return nil
	}
	return s.City
}

func (s *ShipmentDetailDtoDestination) GetState() *string {
	if s == nil {
		return nil
	}
	return s.State
}

func (s *ShipmentDetailDtoDestination) GetPostalCode() *string {
	if s == nil {
		return nil
	}
	return s.PostalCode
}

func (s *ShipmentDetailDtoDestination) GetCountry() *string {
	if s == nil {
		return nil
	}
	return s.Country
}

func (s *ShipmentDetailDtoDestination) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ShipmentDetailDtoDestination) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetName(name *string) {
	s.Name = name
	s.require(shipmentDetailDtoDestinationFieldName)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetLine1(line1 *string) {
	s.Line1 = line1
	s.require(shipmentDetailDtoDestinationFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetLine2(line2 *string) {
	s.Line2 = line2
	s.require(shipmentDetailDtoDestinationFieldLine2)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetCity(city *string) {
	s.City = city
	s.require(shipmentDetailDtoDestinationFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetState(state *string) {
	s.State = state
	s.require(shipmentDetailDtoDestinationFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetPostalCode(postalCode *string) {
	s.PostalCode = postalCode
	s.require(shipmentDetailDtoDestinationFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoDestination) SetCountry(country *string) {
	s.Country = country
	s.require(shipmentDetailDtoDestinationFieldCountry)
}

func (s *ShipmentDetailDtoDestination) UnmarshalJSON(data []byte) error {
	type unmarshaler ShipmentDetailDtoDestination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShipmentDetailDtoDestination(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShipmentDetailDtoDestination) MarshalJSON() ([]byte, error) {
	type embed ShipmentDetailDtoDestination
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShipmentDetailDtoDestination) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	shipmentDetailDtoMailItemsItemFieldID               = big.NewInt(1 << 0)
	shipmentDetailDtoMailItemsItemFieldMailType         = big.NewInt(1 << 1)
	shipmentDetailDtoMailItemsItemFieldSenderName       = big.NewInt(1 << 2)
	shipmentDetailDtoMailItemsItemFieldArrivalDate      = big.NewInt(1 << 3)
	shipmentDetailDtoMailItemsItemFieldEnvelopeImageURL = big.NewInt(1 << 4)
)

type ShipmentDetailDtoMailItemsItem struct {
	// Mail item id (numeric string).
	ID         string  `json:"id" url:"id"`
	MailType   string  `json:"mail_type" url:"mail_type"`
	SenderName *string `json:"sender_name,omitempty" url:"sender_name,omitempty"`
	// When the item arrived at the facility.
	ArrivalDate *time.Time `json:"arrival_date,omitempty" url:"arrival_date,omitempty"`
	// Photo of the item/envelope.
	EnvelopeImageURL *string `json:"envelope_image_url,omitempty" url:"envelope_image_url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShipmentDetailDtoMailItemsItem) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ShipmentDetailDtoMailItemsItem) GetMailType() string {
	if s == nil {
		return ""
	}
	return s.MailType
}

func (s *ShipmentDetailDtoMailItemsItem) GetSenderName() *string {
	if s == nil {
		return nil
	}
	return s.SenderName
}

func (s *ShipmentDetailDtoMailItemsItem) GetArrivalDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.ArrivalDate
}

func (s *ShipmentDetailDtoMailItemsItem) GetEnvelopeImageURL() *string {
	if s == nil {
		return nil
	}
	return s.EnvelopeImageURL
}

func (s *ShipmentDetailDtoMailItemsItem) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ShipmentDetailDtoMailItemsItem) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoMailItemsItem) SetID(id string) {
	s.ID = id
	s.require(shipmentDetailDtoMailItemsItemFieldID)
}

// SetMailType sets the MailType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoMailItemsItem) SetMailType(mailType string) {
	s.MailType = mailType
	s.require(shipmentDetailDtoMailItemsItemFieldMailType)
}

// SetSenderName sets the SenderName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoMailItemsItem) SetSenderName(senderName *string) {
	s.SenderName = senderName
	s.require(shipmentDetailDtoMailItemsItemFieldSenderName)
}

// SetArrivalDate sets the ArrivalDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoMailItemsItem) SetArrivalDate(arrivalDate *time.Time) {
	s.ArrivalDate = arrivalDate
	s.require(shipmentDetailDtoMailItemsItemFieldArrivalDate)
}

// SetEnvelopeImageURL sets the EnvelopeImageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentDetailDtoMailItemsItem) SetEnvelopeImageURL(envelopeImageURL *string) {
	s.EnvelopeImageURL = envelopeImageURL
	s.require(shipmentDetailDtoMailItemsItemFieldEnvelopeImageURL)
}

func (s *ShipmentDetailDtoMailItemsItem) UnmarshalJSON(data []byte) error {
	type embed ShipmentDetailDtoMailItemsItem
	var unmarshaler = struct {
		embed
		ArrivalDate *internal.DateTime `json:"arrival_date,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = ShipmentDetailDtoMailItemsItem(unmarshaler.embed)
	s.ArrivalDate = unmarshaler.ArrivalDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShipmentDetailDtoMailItemsItem) MarshalJSON() ([]byte, error) {
	type embed ShipmentDetailDtoMailItemsItem
	var marshaler = struct {
		embed
		ArrivalDate *internal.DateTime `json:"arrival_date,omitempty"`
	}{
		embed:       embed(*s),
		ArrivalDate: internal.NewOptionalDateTime(s.ArrivalDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShipmentDetailDtoMailItemsItem) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment.
type ShipmentDetailDtoStatus string

const (
	ShipmentDetailDtoStatusShipped       ShipmentDetailDtoStatus = "shipped"
	ShipmentDetailDtoStatusInProgress    ShipmentDetailDtoStatus = "in_progress"
	ShipmentDetailDtoStatusPaymentFailed ShipmentDetailDtoStatus = "payment_failed"
	ShipmentDetailDtoStatusRejected      ShipmentDetailDtoStatus = "rejected"
)

func NewShipmentDetailDtoStatusFromString(s string) (ShipmentDetailDtoStatus, error) {
	switch s {
	case "shipped":
		return ShipmentDetailDtoStatusShipped, nil
	case "in_progress":
		return ShipmentDetailDtoStatusInProgress, nil
	case "payment_failed":
		return ShipmentDetailDtoStatusPaymentFailed, nil
	case "rejected":
		return ShipmentDetailDtoStatusRejected, nil
	}
	var t ShipmentDetailDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ShipmentDetailDtoStatus) Ptr() *ShipmentDetailDtoStatus {
	return &s
}

type ShipmentDetailDtoType string

const (
	ShipmentDetailDtoTypeShipment       ShipmentDetailDtoType = "shipment"
	ShipmentDetailDtoTypeReturnToSender ShipmentDetailDtoType = "return_to_sender"
	ShipmentDetailDtoTypeCheckDeposit   ShipmentDetailDtoType = "check_deposit"
	ShipmentDetailDtoTypePickup         ShipmentDetailDtoType = "pickup"
)

func NewShipmentDetailDtoTypeFromString(s string) (ShipmentDetailDtoType, error) {
	switch s {
	case "shipment":
		return ShipmentDetailDtoTypeShipment, nil
	case "return_to_sender":
		return ShipmentDetailDtoTypeReturnToSender, nil
	case "check_deposit":
		return ShipmentDetailDtoTypeCheckDeposit, nil
	case "pickup":
		return ShipmentDetailDtoTypePickup, nil
	}
	var t ShipmentDetailDtoType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ShipmentDetailDtoType) Ptr() *ShipmentDetailDtoType {
	return &s
}

var (
	shipmentPageDtoFieldData       = big.NewInt(1 << 0)
	shipmentPageDtoFieldNextCursor = big.NewInt(1 << 1)
	shipmentPageDtoFieldTotalCount = big.NewInt(1 << 2)
)

type ShipmentPageDto struct {
	Data []*ShipmentPageDtoDataItem `json:"data" url:"data"`
	// Pass as `?cursor=` to fetch the next page. Null on the last page.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// Total number of items matching this query across all pages.
	TotalCount int `json:"total_count" url:"total_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShipmentPageDto) GetData() []*ShipmentPageDtoDataItem {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *ShipmentPageDto) GetNextCursor() *string {
	if s == nil {
		return nil
	}
	return s.NextCursor
}

func (s *ShipmentPageDto) GetTotalCount() int {
	if s == nil {
		return 0
	}
	return s.TotalCount
}

func (s *ShipmentPageDto) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ShipmentPageDto) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDto) SetData(data []*ShipmentPageDtoDataItem) {
	s.Data = data
	s.require(shipmentPageDtoFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDto) SetNextCursor(nextCursor *string) {
	s.NextCursor = nextCursor
	s.require(shipmentPageDtoFieldNextCursor)
}

// SetTotalCount sets the TotalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDto) SetTotalCount(totalCount int) {
	s.TotalCount = totalCount
	s.require(shipmentPageDtoFieldTotalCount)
}

func (s *ShipmentPageDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ShipmentPageDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShipmentPageDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShipmentPageDto) MarshalJSON() ([]byte, error) {
	type embed ShipmentPageDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShipmentPageDto) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	shipmentPageDtoDataItemFieldID                          = big.NewInt(1 << 0)
	shipmentPageDtoDataItemFieldType                        = big.NewInt(1 << 1)
	shipmentPageDtoDataItemFieldStatus                      = big.NewInt(1 << 2)
	shipmentPageDtoDataItemFieldTrackingNumber              = big.NewInt(1 << 3)
	shipmentPageDtoDataItemFieldServiceName                 = big.NewInt(1 << 4)
	shipmentPageDtoDataItemFieldDestination                 = big.NewInt(1 << 5)
	shipmentPageDtoDataItemFieldItemCount                   = big.NewInt(1 << 6)
	shipmentPageDtoDataItemFieldRequestedShipDate           = big.NewInt(1 << 7)
	shipmentPageDtoDataItemFieldCreatedOn                   = big.NewInt(1 << 8)
	shipmentPageDtoDataItemFieldDepositCheckSlipCompanyName = big.NewInt(1 << 9)
)

type ShipmentPageDtoDataItem struct {
	// Shipment id (UUID).
	ID   string                      `json:"id" url:"id"`
	Type ShipmentPageDtoDataItemType `json:"type" url:"type"`
	// Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment.
	Status ShipmentPageDtoDataItemStatus `json:"status" url:"status"`
	// Carrier tracking number, once the shipment is on its way.
	TrackingNumber *string `json:"tracking_number,omitempty" url:"tracking_number,omitempty"`
	// Carrier service used (e.g. "FedEx International Priority").
	ServiceName *string `json:"service_name,omitempty" url:"service_name,omitempty"`
	// Where it ships to. Only present for `shipment` and `check_deposit` types — returns go back to the sender and pickups happen at the facility.
	Destination *ShipmentPageDtoDataItemDestination `json:"destination,omitempty" url:"destination,omitempty"`
	// Number of mail items packed into the request.
	ItemCount int `json:"item_count" url:"item_count"`
	// The ship-out date the customer asked for.
	RequestedShipDate *time.Time `json:"requested_ship_date,omitempty" url:"requested_ship_date,omitempty"`
	// When the request was made.
	CreatedOn time.Time `json:"created_on" url:"created_on"`
	// `check_deposit` only.
	DepositCheckSlipCompanyName *string `json:"deposit_check_slip_company_name,omitempty" url:"deposit_check_slip_company_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShipmentPageDtoDataItem) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ShipmentPageDtoDataItem) GetType() ShipmentPageDtoDataItemType {
	if s == nil {
		return ""
	}
	return s.Type
}

func (s *ShipmentPageDtoDataItem) GetStatus() ShipmentPageDtoDataItemStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ShipmentPageDtoDataItem) GetTrackingNumber() *string {
	if s == nil {
		return nil
	}
	return s.TrackingNumber
}

func (s *ShipmentPageDtoDataItem) GetServiceName() *string {
	if s == nil {
		return nil
	}
	return s.ServiceName
}

func (s *ShipmentPageDtoDataItem) GetDestination() *ShipmentPageDtoDataItemDestination {
	if s == nil {
		return nil
	}
	return s.Destination
}

func (s *ShipmentPageDtoDataItem) GetItemCount() int {
	if s == nil {
		return 0
	}
	return s.ItemCount
}

func (s *ShipmentPageDtoDataItem) GetRequestedShipDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.RequestedShipDate
}

func (s *ShipmentPageDtoDataItem) GetCreatedOn() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedOn
}

func (s *ShipmentPageDtoDataItem) GetDepositCheckSlipCompanyName() *string {
	if s == nil {
		return nil
	}
	return s.DepositCheckSlipCompanyName
}

func (s *ShipmentPageDtoDataItem) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ShipmentPageDtoDataItem) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetID(id string) {
	s.ID = id
	s.require(shipmentPageDtoDataItemFieldID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetType(type_ ShipmentPageDtoDataItemType) {
	s.Type = type_
	s.require(shipmentPageDtoDataItemFieldType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetStatus(status ShipmentPageDtoDataItemStatus) {
	s.Status = status
	s.require(shipmentPageDtoDataItemFieldStatus)
}

// SetTrackingNumber sets the TrackingNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetTrackingNumber(trackingNumber *string) {
	s.TrackingNumber = trackingNumber
	s.require(shipmentPageDtoDataItemFieldTrackingNumber)
}

// SetServiceName sets the ServiceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetServiceName(serviceName *string) {
	s.ServiceName = serviceName
	s.require(shipmentPageDtoDataItemFieldServiceName)
}

// SetDestination sets the Destination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetDestination(destination *ShipmentPageDtoDataItemDestination) {
	s.Destination = destination
	s.require(shipmentPageDtoDataItemFieldDestination)
}

// SetItemCount sets the ItemCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetItemCount(itemCount int) {
	s.ItemCount = itemCount
	s.require(shipmentPageDtoDataItemFieldItemCount)
}

// SetRequestedShipDate sets the RequestedShipDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetRequestedShipDate(requestedShipDate *time.Time) {
	s.RequestedShipDate = requestedShipDate
	s.require(shipmentPageDtoDataItemFieldRequestedShipDate)
}

// SetCreatedOn sets the CreatedOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetCreatedOn(createdOn time.Time) {
	s.CreatedOn = createdOn
	s.require(shipmentPageDtoDataItemFieldCreatedOn)
}

// SetDepositCheckSlipCompanyName sets the DepositCheckSlipCompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItem) SetDepositCheckSlipCompanyName(depositCheckSlipCompanyName *string) {
	s.DepositCheckSlipCompanyName = depositCheckSlipCompanyName
	s.require(shipmentPageDtoDataItemFieldDepositCheckSlipCompanyName)
}

func (s *ShipmentPageDtoDataItem) UnmarshalJSON(data []byte) error {
	type embed ShipmentPageDtoDataItem
	var unmarshaler = struct {
		embed
		RequestedShipDate *internal.DateTime `json:"requested_ship_date,omitempty"`
		CreatedOn         *internal.DateTime `json:"created_on"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = ShipmentPageDtoDataItem(unmarshaler.embed)
	s.RequestedShipDate = unmarshaler.RequestedShipDate.TimePtr()
	s.CreatedOn = unmarshaler.CreatedOn.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShipmentPageDtoDataItem) MarshalJSON() ([]byte, error) {
	type embed ShipmentPageDtoDataItem
	var marshaler = struct {
		embed
		RequestedShipDate *internal.DateTime `json:"requested_ship_date,omitempty"`
		CreatedOn         *internal.DateTime `json:"created_on"`
	}{
		embed:             embed(*s),
		RequestedShipDate: internal.NewOptionalDateTime(s.RequestedShipDate),
		CreatedOn:         internal.NewDateTime(s.CreatedOn),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShipmentPageDtoDataItem) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	shipmentPageDtoDataItemDestinationFieldName       = big.NewInt(1 << 0)
	shipmentPageDtoDataItemDestinationFieldLine1      = big.NewInt(1 << 1)
	shipmentPageDtoDataItemDestinationFieldLine2      = big.NewInt(1 << 2)
	shipmentPageDtoDataItemDestinationFieldCity       = big.NewInt(1 << 3)
	shipmentPageDtoDataItemDestinationFieldState      = big.NewInt(1 << 4)
	shipmentPageDtoDataItemDestinationFieldPostalCode = big.NewInt(1 << 5)
	shipmentPageDtoDataItemDestinationFieldCountry    = big.NewInt(1 << 6)
)

type ShipmentPageDtoDataItemDestination struct {
	// Recipient name on the address.
	Name       *string `json:"name,omitempty" url:"name,omitempty"`
	Line1      *string `json:"line1,omitempty" url:"line1,omitempty"`
	Line2      *string `json:"line2,omitempty" url:"line2,omitempty"`
	City       *string `json:"city,omitempty" url:"city,omitempty"`
	State      *string `json:"state,omitempty" url:"state,omitempty"`
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	Country    *string `json:"country,omitempty" url:"country,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ShipmentPageDtoDataItemDestination) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ShipmentPageDtoDataItemDestination) GetLine1() *string {
	if s == nil {
		return nil
	}
	return s.Line1
}

func (s *ShipmentPageDtoDataItemDestination) GetLine2() *string {
	if s == nil {
		return nil
	}
	return s.Line2
}

func (s *ShipmentPageDtoDataItemDestination) GetCity() *string {
	if s == nil {
		return nil
	}
	return s.City
}

func (s *ShipmentPageDtoDataItemDestination) GetState() *string {
	if s == nil {
		return nil
	}
	return s.State
}

func (s *ShipmentPageDtoDataItemDestination) GetPostalCode() *string {
	if s == nil {
		return nil
	}
	return s.PostalCode
}

func (s *ShipmentPageDtoDataItemDestination) GetCountry() *string {
	if s == nil {
		return nil
	}
	return s.Country
}

func (s *ShipmentPageDtoDataItemDestination) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ShipmentPageDtoDataItemDestination) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetName(name *string) {
	s.Name = name
	s.require(shipmentPageDtoDataItemDestinationFieldName)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetLine1(line1 *string) {
	s.Line1 = line1
	s.require(shipmentPageDtoDataItemDestinationFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetLine2(line2 *string) {
	s.Line2 = line2
	s.require(shipmentPageDtoDataItemDestinationFieldLine2)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetCity(city *string) {
	s.City = city
	s.require(shipmentPageDtoDataItemDestinationFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetState(state *string) {
	s.State = state
	s.require(shipmentPageDtoDataItemDestinationFieldState)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetPostalCode(postalCode *string) {
	s.PostalCode = postalCode
	s.require(shipmentPageDtoDataItemDestinationFieldPostalCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ShipmentPageDtoDataItemDestination) SetCountry(country *string) {
	s.Country = country
	s.require(shipmentPageDtoDataItemDestinationFieldCountry)
}

func (s *ShipmentPageDtoDataItemDestination) UnmarshalJSON(data []byte) error {
	type unmarshaler ShipmentPageDtoDataItemDestination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ShipmentPageDtoDataItemDestination(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ShipmentPageDtoDataItemDestination) MarshalJSON() ([]byte, error) {
	type embed ShipmentPageDtoDataItemDestination
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ShipmentPageDtoDataItemDestination) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Customer-facing status group — `in_progress` covers every internal workflow state between request and shipment.
type ShipmentPageDtoDataItemStatus string

const (
	ShipmentPageDtoDataItemStatusShipped       ShipmentPageDtoDataItemStatus = "shipped"
	ShipmentPageDtoDataItemStatusInProgress    ShipmentPageDtoDataItemStatus = "in_progress"
	ShipmentPageDtoDataItemStatusPaymentFailed ShipmentPageDtoDataItemStatus = "payment_failed"
	ShipmentPageDtoDataItemStatusRejected      ShipmentPageDtoDataItemStatus = "rejected"
)

func NewShipmentPageDtoDataItemStatusFromString(s string) (ShipmentPageDtoDataItemStatus, error) {
	switch s {
	case "shipped":
		return ShipmentPageDtoDataItemStatusShipped, nil
	case "in_progress":
		return ShipmentPageDtoDataItemStatusInProgress, nil
	case "payment_failed":
		return ShipmentPageDtoDataItemStatusPaymentFailed, nil
	case "rejected":
		return ShipmentPageDtoDataItemStatusRejected, nil
	}
	var t ShipmentPageDtoDataItemStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ShipmentPageDtoDataItemStatus) Ptr() *ShipmentPageDtoDataItemStatus {
	return &s
}

type ShipmentPageDtoDataItemType string

const (
	ShipmentPageDtoDataItemTypeShipment       ShipmentPageDtoDataItemType = "shipment"
	ShipmentPageDtoDataItemTypeReturnToSender ShipmentPageDtoDataItemType = "return_to_sender"
	ShipmentPageDtoDataItemTypeCheckDeposit   ShipmentPageDtoDataItemType = "check_deposit"
	ShipmentPageDtoDataItemTypePickup         ShipmentPageDtoDataItemType = "pickup"
)

func NewShipmentPageDtoDataItemTypeFromString(s string) (ShipmentPageDtoDataItemType, error) {
	switch s {
	case "shipment":
		return ShipmentPageDtoDataItemTypeShipment, nil
	case "return_to_sender":
		return ShipmentPageDtoDataItemTypeReturnToSender, nil
	case "check_deposit":
		return ShipmentPageDtoDataItemTypeCheckDeposit, nil
	case "pickup":
		return ShipmentPageDtoDataItemTypePickup, nil
	}
	var t ShipmentPageDtoDataItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ShipmentPageDtoDataItemType) Ptr() *ShipmentPageDtoDataItemType {
	return &s
}

type ShipmentsListRequestStatusItem string

const (
	ShipmentsListRequestStatusItemShipped       ShipmentsListRequestStatusItem = "shipped"
	ShipmentsListRequestStatusItemInProgress    ShipmentsListRequestStatusItem = "in_progress"
	ShipmentsListRequestStatusItemPaymentFailed ShipmentsListRequestStatusItem = "payment_failed"
	ShipmentsListRequestStatusItemRejected      ShipmentsListRequestStatusItem = "rejected"
)

func NewShipmentsListRequestStatusItemFromString(s string) (ShipmentsListRequestStatusItem, error) {
	switch s {
	case "shipped":
		return ShipmentsListRequestStatusItemShipped, nil
	case "in_progress":
		return ShipmentsListRequestStatusItemInProgress, nil
	case "payment_failed":
		return ShipmentsListRequestStatusItemPaymentFailed, nil
	case "rejected":
		return ShipmentsListRequestStatusItemRejected, nil
	}
	var t ShipmentsListRequestStatusItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ShipmentsListRequestStatusItem) Ptr() *ShipmentsListRequestStatusItem {
	return &s
}

type ShipmentsListRequestTypeItem string

const (
	ShipmentsListRequestTypeItemShipment       ShipmentsListRequestTypeItem = "shipment"
	ShipmentsListRequestTypeItemReturnToSender ShipmentsListRequestTypeItem = "return_to_sender"
	ShipmentsListRequestTypeItemCheckDeposit   ShipmentsListRequestTypeItem = "check_deposit"
	ShipmentsListRequestTypeItemPickup         ShipmentsListRequestTypeItem = "pickup"
)

func NewShipmentsListRequestTypeItemFromString(s string) (ShipmentsListRequestTypeItem, error) {
	switch s {
	case "shipment":
		return ShipmentsListRequestTypeItemShipment, nil
	case "return_to_sender":
		return ShipmentsListRequestTypeItemReturnToSender, nil
	case "check_deposit":
		return ShipmentsListRequestTypeItemCheckDeposit, nil
	case "pickup":
		return ShipmentsListRequestTypeItemPickup, nil
	}
	var t ShipmentsListRequestTypeItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ShipmentsListRequestTypeItem) Ptr() *ShipmentsListRequestTypeItem {
	return &s
}
