// Code generated by Fern. DO NOT EDIT.

package usgm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/usgm/usgm-go/internal"
	big "math/big"
	time "time"
)

var (
	problemDetailsDtoFieldType      = big.NewInt(1 << 0)
	problemDetailsDtoFieldTitle     = big.NewInt(1 << 1)
	problemDetailsDtoFieldStatus    = big.NewInt(1 << 2)
	problemDetailsDtoFieldCode      = big.NewInt(1 << 3)
	problemDetailsDtoFieldRequestID = big.NewInt(1 << 4)
	problemDetailsDtoFieldDetail    = big.NewInt(1 << 5)
	problemDetailsDtoFieldInstance  = big.NewInt(1 << 6)
	problemDetailsDtoFieldErrors    = big.NewInt(1 << 7)
)

type ProblemDetailsDto struct {
	Type      string                         `json:"type" url:"type"`
	Title     string                         `json:"title" url:"title"`
	Status    int                            `json:"status" url:"status"`
	Code      string                         `json:"code" url:"code"`
	RequestID string                         `json:"request_id" url:"request_id"`
	Detail    *string                        `json:"detail,omitempty" url:"detail,omitempty"`
	Instance  *string                        `json:"instance,omitempty" url:"instance,omitempty"`
	Errors    []*ProblemDetailsDtoErrorsItem `json:"errors,omitempty" url:"errors,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProblemDetailsDto) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *ProblemDetailsDto) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *ProblemDetailsDto) GetStatus() int {
	if p == nil {
		return 0
	}
	return p.Status
}

func (p *ProblemDetailsDto) GetCode() string {
	if p == nil {
		return ""
	}
	return p.Code
}

func (p *ProblemDetailsDto) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}

func (p *ProblemDetailsDto) GetDetail() *string {
	if p == nil {
		return nil
	}
	return p.Detail
}

func (p *ProblemDetailsDto) GetInstance() *string {
	if p == nil {
		return nil
	}
	return p.Instance
}

func (p *ProblemDetailsDto) GetErrors() []*ProblemDetailsDtoErrorsItem {
	if p == nil {
		return nil
	}
	return p.Errors
}

func (p *ProblemDetailsDto) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProblemDetailsDto) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetType(type_ string) {
	p.Type = type_
	p.require(problemDetailsDtoFieldType)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetTitle(title string) {
	p.Title = title
	p.require(problemDetailsDtoFieldTitle)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetStatus(status int) {
	p.Status = status
	p.require(problemDetailsDtoFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetCode(code string) {
	p.Code = code
	p.require(problemDetailsDtoFieldCode)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetRequestID(requestID string) {
	p.RequestID = requestID
	p.require(problemDetailsDtoFieldRequestID)
}

// SetDetail sets the Detail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetDetail(detail *string) {
	p.Detail = detail
	p.require(problemDetailsDtoFieldDetail)
}

// SetInstance sets the Instance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetInstance(instance *string) {
	p.Instance = instance
	p.require(problemDetailsDtoFieldInstance)
}

// SetErrors sets the Errors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDto) SetErrors(errors []*ProblemDetailsDtoErrorsItem) {
	p.Errors = errors
	p.require(problemDetailsDtoFieldErrors)
}

func (p *ProblemDetailsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ProblemDetailsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProblemDetailsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProblemDetailsDto) MarshalJSON() ([]byte, error) {
	type embed ProblemDetailsDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProblemDetailsDto) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	problemDetailsDtoErrorsItemFieldField   = big.NewInt(1 << 0)
	problemDetailsDtoErrorsItemFieldCode    = big.NewInt(1 << 1)
	problemDetailsDtoErrorsItemFieldMessage = big.NewInt(1 << 2)
)

type ProblemDetailsDtoErrorsItem struct {
	Field   string  `json:"field" url:"field"`
	Code    *string `json:"code,omitempty" url:"code,omitempty"`
	Message string  `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProblemDetailsDtoErrorsItem) GetField() string {
	if p == nil {
		return ""
	}
	return p.Field
}

func (p *ProblemDetailsDtoErrorsItem) GetCode() *string {
	if p == nil {
		return nil
	}
	return p.Code
}

func (p *ProblemDetailsDtoErrorsItem) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *ProblemDetailsDtoErrorsItem) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProblemDetailsDtoErrorsItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetField sets the Field field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDtoErrorsItem) SetField(field string) {
	p.Field = field
	p.require(problemDetailsDtoErrorsItemFieldField)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDtoErrorsItem) SetCode(code *string) {
	p.Code = code
	p.require(problemDetailsDtoErrorsItemFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProblemDetailsDtoErrorsItem) SetMessage(message string) {
	p.Message = message
	p.require(problemDetailsDtoErrorsItemFieldMessage)
}

func (p *ProblemDetailsDtoErrorsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ProblemDetailsDtoErrorsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProblemDetailsDtoErrorsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProblemDetailsDtoErrorsItem) MarshalJSON() ([]byte, error) {
	type embed ProblemDetailsDtoErrorsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProblemDetailsDtoErrorsItem) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	scanDtoFieldID              = big.NewInt(1 << 0)
	scanDtoFieldMailID          = big.NewInt(1 << 1)
	scanDtoFieldType            = big.NewInt(1 << 2)
	scanDtoFieldStatus          = big.NewInt(1 << 3)
	scanDtoFieldIsExpedited     = big.NewInt(1 << 4)
	scanDtoFieldInstruction     = big.NewInt(1 << 5)
	scanDtoFieldRejectReason    = big.NewInt(1 << 6)
	scanDtoFieldLabel           = big.NewInt(1 << 7)
	scanDtoFieldStatusUpdatedAt = big.NewInt(1 << 8)
	scanDtoFieldAutoDeleteOn    = big.NewInt(1 << 9)
	scanDtoFieldCreatedAt       = big.NewInt(1 << 10)
	scanDtoFieldUpdatedAt       = big.NewInt(1 << 11)
)

type ScanDto struct {
	// Scan id (UUID).
	ID string `json:"id" url:"id"`
	// Id of the scanned mail item (numeric string).
	MailID string `json:"mail_id" url:"mail_id"`
	// `SCAN_REQUEST` (scan the item) or `UNBOXING_REQUEST` (open it and scan the contents).
	Type string `json:"type" url:"type"`
	// `IN_PROCESS`, `COMPLETED`, `CANCELLED`, `REJECTED`, `DELETED` or `RESTORING`.
	Status      string  `json:"status" url:"status"`
	IsExpedited bool    `json:"is_expedited" url:"is_expedited"`
	Instruction *string `json:"instruction,omitempty" url:"instruction,omitempty"`
	// Why the request was rejected. Null unless `status` is `REJECTED`.
	RejectReason *string `json:"reject_reason,omitempty" url:"reject_reason,omitempty"`
	// Short AI-generated label of the scanned document (e.g. "Insurance"). Null until generated; requires a plan that includes scan labeling.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// When the current `status` was reached — for completed scans, the completion time.
	StatusUpdatedAt *time.Time `json:"status_updated_at,omitempty" url:"status_updated_at,omitempty"`
	// When the scan file is permanently deleted — download it before this date. Null when no deletion is scheduled.
	AutoDeleteOn *time.Time `json:"auto_delete_on,omitempty" url:"auto_delete_on,omitempty"`
	CreatedAt    time.Time  `json:"created_at" url:"created_at"`
	// Last change of any kind — use `status_updated_at` for status timing.
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ScanDto) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ScanDto) GetMailID() string {
	if s == nil {
		return ""
	}
	return s.MailID
}

func (s *ScanDto) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}

func (s *ScanDto) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *ScanDto) GetIsExpedited() bool {
	if s == nil {
		return false
	}
	return s.IsExpedited
}

func (s *ScanDto) GetInstruction() *string {
	if s == nil {
		return nil
	}
	return s.Instruction
}

func (s *ScanDto) GetRejectReason() *string {
	if s == nil {
		return nil
	}
	return s.RejectReason
}

func (s *ScanDto) GetLabel() *string {
	if s == nil {
		return nil
	}
	return s.Label
}

func (s *ScanDto) GetStatusUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.StatusUpdatedAt
}

func (s *ScanDto) GetAutoDeleteOn() *time.Time {
	if s == nil {
		return nil
	}
	return s.AutoDeleteOn
}

func (s *ScanDto) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *ScanDto) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}

func (s *ScanDto) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ScanDto) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetID(id string) {
	s.ID = id
	s.require(scanDtoFieldID)
}

// SetMailID sets the MailID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetMailID(mailID string) {
	s.MailID = mailID
	s.require(scanDtoFieldMailID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetType(type_ string) {
	s.Type = type_
	s.require(scanDtoFieldType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetStatus(status string) {
	s.Status = status
	s.require(scanDtoFieldStatus)
}

// SetIsExpedited sets the IsExpedited field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetIsExpedited(isExpedited bool) {
	s.IsExpedited = isExpedited
	s.require(scanDtoFieldIsExpedited)
}

// SetInstruction sets the Instruction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetInstruction(instruction *string) {
	s.Instruction = instruction
	s.require(scanDtoFieldInstruction)
}

// SetRejectReason sets the RejectReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetRejectReason(rejectReason *string) {
	s.RejectReason = rejectReason
	s.require(scanDtoFieldRejectReason)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetLabel(label *string) {
	s.Label = label
	s.require(scanDtoFieldLabel)
}

// SetStatusUpdatedAt sets the StatusUpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetStatusUpdatedAt(statusUpdatedAt *time.Time) {
	s.StatusUpdatedAt = statusUpdatedAt
	s.require(scanDtoFieldStatusUpdatedAt)
}

// SetAutoDeleteOn sets the AutoDeleteOn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetAutoDeleteOn(autoDeleteOn *time.Time) {
	s.AutoDeleteOn = autoDeleteOn
	s.require(scanDtoFieldAutoDeleteOn)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetCreatedAt(createdAt time.Time) {
	s.CreatedAt = createdAt
	s.require(scanDtoFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScanDto) SetUpdatedAt(updatedAt time.Time) {
	s.UpdatedAt = updatedAt
	s.require(scanDtoFieldUpdatedAt)
}

func (s *ScanDto) UnmarshalJSON(data []byte) error {
	type embed ScanDto
	var unmarshaler = struct {
		embed
		StatusUpdatedAt *internal.DateTime `json:"status_updated_at,omitempty"`
		AutoDeleteOn    *internal.DateTime `json:"auto_delete_on,omitempty"`
		CreatedAt       *internal.DateTime `json:"created_at"`
		UpdatedAt       *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = ScanDto(unmarshaler.embed)
	s.StatusUpdatedAt = unmarshaler.StatusUpdatedAt.TimePtr()
	s.AutoDeleteOn = unmarshaler.AutoDeleteOn.TimePtr()
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	s.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ScanDto) MarshalJSON() ([]byte, error) {
	type embed ScanDto
	var marshaler = struct {
		embed
		StatusUpdatedAt *internal.DateTime `json:"status_updated_at,omitempty"`
		AutoDeleteOn    *internal.DateTime `json:"auto_delete_on,omitempty"`
		CreatedAt       *internal.DateTime `json:"created_at"`
		UpdatedAt       *internal.DateTime `json:"updated_at"`
	}{
		embed:           embed(*s),
		StatusUpdatedAt: internal.NewOptionalDateTime(s.StatusUpdatedAt),
		AutoDeleteOn:    internal.NewOptionalDateTime(s.AutoDeleteOn),
		CreatedAt:       internal.NewDateTime(s.CreatedAt),
		UpdatedAt:       internal.NewDateTime(s.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ScanDto) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
