// Code generated by Fern. DO NOT EDIT.

package mails

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List your mail items with filtering, search, sorting and cursor pagination
func (c *Client) List(
	ctx context.Context,
	request *usgm.MailsListRequest,
	opts ...option.RequestOption,
) (*usgm.MailPageDto, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve full detail for one mail item, including dimensions, weight and folder
func (c *Client) Get(
	ctx context.Context,
	request *usgm.MailsGetRequest,
	opts ...option.RequestOption,
) (*usgm.MailDetailDto, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Mark the item read/unread and/or move it into a folder
func (c *Client) Update(
	ctx context.Context,
	request *usgm.UpdateMailDto,
	opts ...option.RequestOption,
) (*usgm.MailDetailDto, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Move the item out of your active inbox into the archive
func (c *Client) Archive(
	ctx context.Context,
	request *usgm.MailsArchiveRequest,
	opts ...option.RequestOption,
) (*usgm.MailDetailDto, error) {
	response, err := c.WithRawResponse.Archive(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Restore an archived item back to its previous inbox status
func (c *Client) Unarchive(
	ctx context.Context,
	request *usgm.MailsUnarchiveRequest,
	opts ...option.RequestOption,
) (*usgm.MailDetailDto, error) {
	response, err := c.WithRawResponse.Unarchive(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Request the mailroom to discard the physical item; destructive, reverse with undiscard within 7 days after the discard request. After 7 days the mail item will be permanently and securely shredded and discarded
func (c *Client) Discard(
	ctx context.Context,
	request *usgm.MailsDiscardRequest,
	opts ...option.RequestOption,
) (*usgm.MailDetailDto, error) {
	response, err := c.WithRawResponse.Discard(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancel a pending discard request and keep the item
func (c *Client) Undiscard(
	ctx context.Context,
	request *usgm.MailsUndiscardRequest,
	opts ...option.RequestOption,
) (*usgm.MailDetailDto, error) {
	response, err := c.WithRawResponse.Undiscard(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
