// Code generated by Fern. DO NOT EDIT.

package folders

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// All your mail folders, returned unpaginated
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*usgm.FolderListDto, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new mail folder with a name and optional color
func (c *Client) Create(
	ctx context.Context,
	request *usgm.CreateFolderDto,
	opts ...option.RequestOption,
) (*usgm.FolderDto, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve one mail folder by its id
func (c *Client) Get(
	ctx context.Context,
	request *usgm.FoldersGetRequest,
	opts ...option.RequestOption,
) (*usgm.FolderDto, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a folder and unfile its mail, which is not deleted
func (c *Client) Delete(
	ctx context.Context,
	request *usgm.FoldersDeleteRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Rename a folder or change its color
func (c *Client) Update(
	ctx context.Context,
	request *usgm.UpdateFolderDto,
	opts ...option.RequestOption,
) (*usgm.FolderDto, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
