// Code generated by Fern. DO NOT EDIT.

package account

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Your account profile, including name, email, status, and PMB number
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*usgm.AccountDto, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Your current USGM address, including PMB number
func (c *Client) Mailingaddress(
	ctx context.Context,
	opts ...option.RequestOption,
) (*usgm.MailingAddressDto, error) {
	response, err := c.WithRawResponse.Mailingaddress(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
