// Code generated by Fern. DO NOT EDIT.

package scans

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List your scan and open-and-scan requests, with filtering, search and pagination
func (c *Client) List(
	ctx context.Context,
	request *usgm.ScansListRequest,
	opts ...option.RequestOption,
) (*usgm.ScanPageDto, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Request a scan or open-and-scan of a mail item; this is a billable action
func (c *Client) Create(
	ctx context.Context,
	request *usgm.CreateScanDto,
	opts ...option.RequestOption,
) (*usgm.ScanDto, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve one scan request by its id, including status and AI label
func (c *Client) Get(
	ctx context.Context,
	request *usgm.ScansGetRequest,
	opts ...option.RequestOption,
) (*usgm.ScanDto, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently delete a scan and remove its stored file; this cannot be undone
func (c *Client) Delete(
	ctx context.Context,
	request *usgm.ScansDeleteRequest,
	opts ...option.RequestOption,
) (*usgm.ScanDto, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Return a short-lived signed URL to download the scanned document; fetch it promptly
func (c *Client) File(
	ctx context.Context,
	request *usgm.ScansFileRequest,
	opts ...option.RequestOption,
) (*usgm.ScanFileDto, error) {
	response, err := c.WithRawResponse.File(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Return the AI-generated label and bullet summary of the scanned document
func (c *Client) Summary(
	ctx context.Context,
	request *usgm.ScansSummaryRequest,
	opts ...option.RequestOption,
) (*usgm.ScanSummaryDto, error) {
	response, err := c.WithRawResponse.Summary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancel a scan request you no longer need. Valid only for scan requests in in_process status
func (c *Client) Cancel(
	ctx context.Context,
	request *usgm.ScansCancelRequest,
	opts ...option.RequestOption,
) (*usgm.ScanDto, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
