// Code generated by Fern. DO NOT EDIT.

package shipments

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Read-only list of your shipment requests, filterable by type and status
func (c *Client) List(
	ctx context.Context,
	request *usgm.ShipmentsListRequest,
	opts ...option.RequestOption,
) (*usgm.ShipmentPageDto, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Read-only details of one shipment, including its packed mail items
func (c *Client) Get(
	ctx context.Context,
	request *usgm.ShipmentsGetRequest,
	opts ...option.RequestOption,
) (*usgm.ShipmentDetailDto, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
