// Code generated by Fern. DO NOT EDIT.

package addresses

import (
	context "context"

	usgm "github.com/usgm/usgm-go"
	core "github.com/usgm/usgm-go/core"
	internal "github.com/usgm/usgm-go/internal"
	option "github.com/usgm/usgm-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List your shipping and deposit addresses, optionally filtered by type
func (c *Client) List(
	ctx context.Context,
	request *usgm.AddressesListRequest,
	opts ...option.RequestOption,
) (*usgm.AddressPageDto, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Add a new shipping or check-deposit address to your account
func (c *Client) Create(
	ctx context.Context,
	request *usgm.CreateAddressDto,
	opts ...option.RequestOption,
) (*usgm.AddressDto, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get your default address for a given type, shipping or deposit
func (c *Client) Getdefault(
	ctx context.Context,
	request *usgm.AddressesGetDefaultRequest,
	opts ...option.RequestOption,
) (*usgm.AddressDto, error) {
	response, err := c.WithRawResponse.Getdefault(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve one shipping or deposit address by its id
func (c *Client) Get(
	ctx context.Context,
	request *usgm.AddressesGetRequest,
	opts ...option.RequestOption,
) (*usgm.AddressDto, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently delete an address; this is destructive and cannot be undone
func (c *Client) Delete(
	ctx context.Context,
	request *usgm.AddressesDeleteRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update fields on an existing shipping or deposit address
func (c *Client) Update(
	ctx context.Context,
	request *usgm.UpdateAddressDto,
	opts ...option.RequestOption,
) (*usgm.AddressDto, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Make this address the default for its type, replacing the previous default
func (c *Client) Setdefault(
	ctx context.Context,
	request *usgm.AddressesSetDefaultRequest,
	opts ...option.RequestOption,
) (*usgm.AddressDto, error) {
	response, err := c.WithRawResponse.Setdefault(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
